#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from yacc_syntax.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "yacc_syntax.y"

#include "../../token.c"
#include <stdio.h>     /* C declarations used in actions */
#include <stdlib.h>

void yyerror (char *s); 

int yylex();

void success();

#line 13 "yacc_syntax.y"
typedef union {Token* token;} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	HEXA_VALUE	258
#define	INT_VALUE	259
#define	REAL_VALUE	260
#define	FINAL	261
#define	BOOL_VALUE	262
#define	CONTINUE	263
#define	ID	264
#define	INT	265
#define	REAL	266
#define	BOOL	267
#define	STRING	268
#define	VECTOR	269
#define	PROG	270
#define	INIT	271
#define	END	272
#define	OF	273
#define	VAR	274
#define	LABEL	275
#define	STRUCT	276
#define	TYPE	277
#define	CONST	278
#define	RETURN	279
#define	JUMP	280
#define	FOR	281
#define	WHILE	282
#define	DO	283
#define	REPEAT	284
#define	UNTIL	285
#define	IF	286
#define	THEN	287
#define	ELSE	288
#define	CASE	289
#define	BE	290
#define	FUNC	291
#define	PROC	292
#define	BREAK	293
#define	REF	294
#define	AND	295
#define	OR	296
#define	LESSEQ	297
#define	GREATEQ	298
#define	EQUAL	299
#define	NOTEQ	300
#define	DOUBLEDOT	301
#define	STRING_VALUE	302
#define	CASSIGN	303
#define	WRITE	304
#define	READ	305


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int HEXA_VALUE;
static const int INT_VALUE;
static const int REAL_VALUE;
static const int FINAL;
static const int BOOL_VALUE;
static const int CONTINUE;
static const int ID;
static const int INT;
static const int REAL;
static const int BOOL;
static const int STRING;
static const int VECTOR;
static const int PROG;
static const int INIT;
static const int END;
static const int OF;
static const int VAR;
static const int LABEL;
static const int STRUCT;
static const int TYPE;
static const int CONST;
static const int RETURN;
static const int JUMP;
static const int FOR;
static const int WHILE;
static const int DO;
static const int REPEAT;
static const int UNTIL;
static const int IF;
static const int THEN;
static const int ELSE;
static const int CASE;
static const int BE;
static const int FUNC;
static const int PROC;
static const int BREAK;
static const int REF;
static const int AND;
static const int OR;
static const int LESSEQ;
static const int GREATEQ;
static const int EQUAL;
static const int NOTEQ;
static const int DOUBLEDOT;
static const int STRING_VALUE;
static const int CASSIGN;
static const int WRITE;
static const int READ;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,HEXA_VALUE=258
	,INT_VALUE=259
	,REAL_VALUE=260
	,FINAL=261
	,BOOL_VALUE=262
	,CONTINUE=263
	,ID=264
	,INT=265
	,REAL=266
	,BOOL=267
	,STRING=268
	,VECTOR=269
	,PROG=270
	,INIT=271
	,END=272
	,OF=273
	,VAR=274
	,LABEL=275
	,STRUCT=276
	,TYPE=277
	,CONST=278
	,RETURN=279
	,JUMP=280
	,FOR=281
	,WHILE=282
	,DO=283
	,REPEAT=284
	,UNTIL=285
	,IF=286
	,THEN=287
	,ELSE=288
	,CASE=289
	,BE=290
	,FUNC=291
	,PROC=292
	,BREAK=293
	,REF=294
	,AND=295
	,OR=296
	,LESSEQ=297
	,GREATEQ=298
	,EQUAL=299
	,NOTEQ=300
	,DOUBLEDOT=301
	,STRING_VALUE=302
	,CASSIGN=303
	,WRITE=304
	,READ=305


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::HEXA_VALUE=258;
const int YY_parse_CLASS::INT_VALUE=259;
const int YY_parse_CLASS::REAL_VALUE=260;
const int YY_parse_CLASS::FINAL=261;
const int YY_parse_CLASS::BOOL_VALUE=262;
const int YY_parse_CLASS::CONTINUE=263;
const int YY_parse_CLASS::ID=264;
const int YY_parse_CLASS::INT=265;
const int YY_parse_CLASS::REAL=266;
const int YY_parse_CLASS::BOOL=267;
const int YY_parse_CLASS::STRING=268;
const int YY_parse_CLASS::VECTOR=269;
const int YY_parse_CLASS::PROG=270;
const int YY_parse_CLASS::INIT=271;
const int YY_parse_CLASS::END=272;
const int YY_parse_CLASS::OF=273;
const int YY_parse_CLASS::VAR=274;
const int YY_parse_CLASS::LABEL=275;
const int YY_parse_CLASS::STRUCT=276;
const int YY_parse_CLASS::TYPE=277;
const int YY_parse_CLASS::CONST=278;
const int YY_parse_CLASS::RETURN=279;
const int YY_parse_CLASS::JUMP=280;
const int YY_parse_CLASS::FOR=281;
const int YY_parse_CLASS::WHILE=282;
const int YY_parse_CLASS::DO=283;
const int YY_parse_CLASS::REPEAT=284;
const int YY_parse_CLASS::UNTIL=285;
const int YY_parse_CLASS::IF=286;
const int YY_parse_CLASS::THEN=287;
const int YY_parse_CLASS::ELSE=288;
const int YY_parse_CLASS::CASE=289;
const int YY_parse_CLASS::BE=290;
const int YY_parse_CLASS::FUNC=291;
const int YY_parse_CLASS::PROC=292;
const int YY_parse_CLASS::BREAK=293;
const int YY_parse_CLASS::REF=294;
const int YY_parse_CLASS::AND=295;
const int YY_parse_CLASS::OR=296;
const int YY_parse_CLASS::LESSEQ=297;
const int YY_parse_CLASS::GREATEQ=298;
const int YY_parse_CLASS::EQUAL=299;
const int YY_parse_CLASS::NOTEQ=300;
const int YY_parse_CLASS::DOUBLEDOT=301;
const int YY_parse_CLASS::STRING_VALUE=302;
const int YY_parse_CLASS::CASSIGN=303;
const int YY_parse_CLASS::WRITE=304;
const int YY_parse_CLASS::READ=305;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		312
#define	YYFLAG		-32768
#define	YYNTBASE	67

#define YYTRANSLATE(x) ((unsigned)(x) <= 305 ? yytranslate[x] : 149)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    59,     2,     2,     2,     2,     2,     2,    55,
    56,    64,    62,    57,    63,    66,    65,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    58,    51,    61,
    54,    60,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    52,     2,    53,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     6,    10,    14,    15,    17,    19,    21,    23,    25,
    33,    38,    39,    42,    46,    47,    51,    56,    59,    61,
    64,    65,    70,    72,    74,    78,    81,    85,    88,    89,
    92,    96,    97,   100,   107,   109,   111,   119,   129,   131,
   132,   137,   143,   146,   147,   149,   150,   152,   154,   156,
   158,   160,   162,   164,   167,   169,   171,   174,   177,   178,
   181,   184,   185,   188,   193,   198,   201,   203,   205,   207,
   214,   220,   222,   223,   228,   234,   235,   237,   238,   241,
   245,   246,   253,   258,   260,   262,   270,   273,   274,   282,
   284,   288,   291,   294,   295,   298,   299,   303,   306,   310,
   311,   314,   318,   319,   322,   326,   327,   330,   332,   335,
   339,   343,   347,   351,   355,   359,   360,   363,   367,   371,
   372,   375,   379,   383,   384,   387,   390,   394,   397,   398,
   400,   402,   406,   408,   411,   415,   416,   418,   420,   422,
   424,   426,   428,   430,   432,   434,   436,   438,   440,   443,
   447,   450,   453,   454,   457,   459,   462,   466
};

static const short yyrhs[] = {    15,
     9,    51,    69,    68,     0,    16,    93,    17,     0,    70,
    51,    69,     0,     0,    76,     0,    79,     0,    85,     0,
    86,     0,    87,     0,    14,    52,    73,    53,    18,   141,
    72,     0,    54,    55,   122,    56,     0,     0,    75,    74,
     0,    57,    75,    74,     0,     0,   143,    46,   143,     0,
    19,   139,    58,    77,     0,   141,    78,     0,    71,     0,
    54,   124,     0,     0,    22,     9,    48,    80,     0,    71,
     0,    81,     0,    21,    83,    17,     0,   143,    82,     0,
    55,   139,    56,     0,    46,   143,     0,     0,    76,    84,
     0,    51,    76,    84,     0,     0,    20,   139,     0,    23,
   139,    58,   141,    54,   124,     0,    88,     0,    89,     0,
    37,     9,    55,    90,    56,    69,    68,     0,    36,     9,
    55,    90,    56,    58,   141,    69,    68,     0,    91,     0,
     0,     9,    58,   141,    92,     0,    39,     9,    58,   141,
    92,     0,    57,    91,     0,     0,    95,     0,     0,    38,
     0,    99,     0,   100,     0,   102,     0,    68,     0,   101,
     0,     8,     0,   144,    97,     0,    98,     0,   113,     0,
    94,    96,     0,    51,    95,     0,     0,    58,    94,     0,
    54,   124,     0,     0,    25,     9,     0,    49,    55,   122,
    56,     0,    50,    55,   122,    56,     0,    24,   124,     0,
   103,     0,   111,     0,   112,     0,    26,    55,   104,    56,
    28,    94,     0,   105,    51,   124,    51,   108,     0,   106,
     0,     0,     9,    54,   124,   107,     0,    57,     9,    54,
   124,   107,     0,     0,   109,     0,     0,    95,   110,     0,
    57,    95,   110,     0,     0,    27,    55,   124,    56,    28,
    94,     0,    29,    95,    30,   124,     0,   114,     0,   116,
     0,    31,    55,   124,    56,    32,    94,   115,     0,    33,
    94,     0,     0,    34,    55,   124,    56,    35,   118,   117,
     0,    17,     0,    33,    95,    17,     0,   121,   119,     0,
    51,   120,     0,     0,   121,   119,     0,     0,   147,    58,
    94,     0,   124,   123,     0,    57,   124,   123,     0,     0,
   126,   125,     0,    41,   126,   125,     0,     0,   128,   127,
     0,    40,   128,   127,     0,     0,    59,   129,     0,   129,
     0,   131,   130,     0,    44,   131,   130,     0,    45,   131,
   130,     0,    60,   131,   130,     0,    61,   131,   130,     0,
    42,   131,   130,     0,    43,   131,   130,     0,     0,   133,
   132,     0,    62,   133,   132,     0,    63,   133,   132,     0,
     0,   135,   134,     0,    64,   135,   134,     0,    65,   135,
   134,     0,     0,   143,   136,     0,   137,   138,     0,    55,
   124,    56,     0,    46,   143,     0,     0,    63,     0,    62,
     0,    55,   124,    56,     0,   143,     0,     9,   140,     0,
    57,     9,   140,     0,     0,    10,     0,    11,     0,    12,
     0,    13,     0,     9,     0,     4,     0,     5,     0,     3,
     0,     7,     0,    47,     0,   142,     0,   144,     0,     9,
   145,     0,    52,   122,    53,     0,    66,   144,     0,    55,
   146,     0,     0,   122,    56,     0,    56,     0,   143,   148,
     0,    57,   143,   148,     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    25,    28,    31,    32,    35,    36,    37,    38,    39,    42,
    45,    46,    49,    52,    53,    56,    59,    62,    63,    66,
    67,    70,    73,    74,    77,    78,    79,    82,    83,    86,
    89,    90,    93,    96,    99,   100,   103,   106,   109,   110,
   113,   114,   117,   118,   122,   123,   126,   127,   128,   129,
   130,   131,   132,   133,   134,   135,   138,   141,   142,   145,
   146,   147,   150,   153,   156,   159,   162,   163,   164,   167,
   170,   173,   174,   177,   180,   181,   184,   185,   188,   191,
   192,   195,   198,   201,   202,   205,   208,   209,   213,   216,
   217,   220,   223,   224,   227,   228,   231,   234,   237,   238,
   241,   244,   245,   248,   251,   252,   255,   256,   259,   262,
   263,   264,   265,   266,   267,   268,   271,   274,   275,   276,
   279,   282,   283,   284,   287,   288,   289,   292,   293,   296,
   297,   300,   301,   304,   307,   308,   311,   312,   313,   314,
   315,   318,   319,   320,   321,   322,   325,   326,   329,   332,
   333,   334,   335,   338,   339,   342,   345,   346
};

static const char * const yytname[] = {   "$","error","$illegal.","HEXA_VALUE",
"INT_VALUE","REAL_VALUE","FINAL","BOOL_VALUE","CONTINUE","ID","INT","REAL","BOOL",
"STRING","VECTOR","PROG","INIT","END","OF","VAR","LABEL","STRUCT","TYPE","CONST",
"RETURN","JUMP","FOR","WHILE","DO","REPEAT","UNTIL","IF","THEN","ELSE","CASE",
"BE","FUNC","PROC","BREAK","REF","AND","OR","LESSEQ","GREATEQ","EQUAL","NOTEQ",
"DOUBLEDOT","STRING_VALUE","CASSIGN","WRITE","READ","';'","'['","']'","'='",
"'('","')'","','","':'","'!'","'>'","'<'","'+'","'-'","'*'","'/'","'.'","program",
"block","prevdec","declaration","arraydec","arraydecaux","rangelist","rangelistaux",
"range","vardec","varconstruction","decwithassign","usertype","typedec","typedecaux",
"typedecauxrange","vardeclist","vardeclistaux","labeldec","constdec","abstractiondec",
"procdec","funcdec","parameters","paramsaux","paramslist","prevcommand","callcommand",
"commands","commandsaux","callidbegin","calllabel","write","read","return","loop",
"forloop","forstruct","prevfor","varassignlist","varassignlistaux","posfor",
"posforaux","posforaux2","whileloop","repeatloop","conditional","ifcond","ifcondaux",
"casecond","casecondaux","caselist","caselistaux","caselistaux2","caseclause",
"expressionlist","expressionlistaux","expr","orfact","andfact","andfactaux",
"notfact","expreq","expreqaux","numericexpr","exprsum","exprmul","exprmulaux",
"simpleexpr","optrange","optunary","optbracket","idlist","idlistaux","type",
"literal","atomic","id","idaux","idauxexpraux","atomiclist","atomiclistaux",
""
};
#endif

static const short yyr1[] = {     0,
    67,    68,    69,    69,    70,    70,    70,    70,    70,    71,
    72,    72,    73,    74,    74,    75,    76,    77,    77,    78,
    78,    79,    80,    80,    81,    81,    81,    82,    82,    83,
    84,    84,    85,    86,    87,    87,    88,    89,    90,    90,
    91,    91,    92,    92,    93,    93,    94,    94,    94,    94,
    94,    94,    94,    94,    94,    94,    95,    96,    96,    97,
    97,    97,    98,    99,   100,   101,   102,   102,   102,   103,
   104,   105,   105,   106,   107,   107,   108,   108,   109,   110,
   110,   111,   112,   113,   113,   114,   115,   115,   116,   117,
   117,   118,   119,   119,   120,   120,   121,   122,   123,   123,
   124,   125,   125,   126,   127,   127,   128,   128,   129,   130,
   130,   130,   130,   130,   130,   130,   131,   132,   132,   132,
   133,   134,   134,   134,   135,   135,   135,   136,   136,   137,
   137,   138,   138,   139,   140,   140,   141,   141,   141,   141,
   141,   142,   142,   142,   142,   142,   143,   143,   144,   145,
   145,   145,   145,   146,   146,   147,   148,   148
};

static const short yyr2[] = {     0,
     5,     3,     3,     0,     1,     1,     1,     1,     1,     7,
     4,     0,     2,     3,     0,     3,     4,     2,     1,     2,
     0,     4,     1,     1,     3,     2,     3,     2,     0,     2,
     3,     0,     2,     6,     1,     1,     7,     9,     1,     0,
     4,     5,     2,     0,     1,     0,     1,     1,     1,     1,
     1,     1,     1,     2,     1,     1,     2,     2,     0,     2,
     2,     0,     2,     4,     4,     2,     1,     1,     1,     6,
     5,     1,     0,     4,     5,     0,     1,     0,     2,     3,
     0,     6,     4,     1,     1,     7,     2,     0,     7,     1,
     3,     2,     2,     0,     2,     0,     3,     2,     3,     0,
     2,     3,     0,     2,     3,     0,     2,     1,     2,     3,
     3,     3,     3,     3,     3,     0,     2,     3,     3,     0,
     2,     3,     3,     0,     2,     2,     3,     2,     0,     1,
     1,     3,     1,     2,     3,     0,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     2,     3,
     2,     2,     0,     2,     1,     2,     3,     0
};

static const short yydefact[] = {     0,
     0,     0,     4,     0,     0,     0,     0,     0,     0,     0,
     0,     5,     6,     7,     8,     9,    35,    36,   136,     0,
    33,     0,     0,     0,     0,    46,     1,     4,     0,   134,
     0,     0,     0,    40,    40,    53,   153,     0,     0,     0,
     0,     0,     0,     0,    47,     0,     0,    51,     0,    59,
    45,    55,    48,    49,    52,    50,    67,    68,    69,    56,
    84,    85,    62,     3,   136,   141,   137,   138,   139,   140,
     0,    19,    17,    21,   144,   142,   143,   145,     0,   146,
     0,    23,    22,    24,   147,    29,   148,     0,     0,     0,
     0,    39,     0,     0,     0,     0,   149,     0,     0,   131,
   130,    66,   103,   106,   108,   116,   120,   124,     0,   129,
    63,    73,     0,     0,     0,     0,     0,     0,     2,     0,
    57,     0,     0,    54,   135,     0,     0,    18,    32,     0,
     0,     0,    26,     0,     0,     0,     0,     4,     0,   100,
   155,     0,   152,   151,     0,   107,     0,   101,     0,   104,
     0,     0,     0,     0,     0,     0,   109,     0,     0,   117,
     0,     0,   121,     0,   126,   133,     0,   125,     0,     0,
     0,    72,     0,     0,     0,     0,     0,     0,    58,    61,
    60,     0,    15,     0,    20,     0,    30,    25,    27,    28,
    34,    44,     0,     0,     0,   150,     0,    98,   154,   127,
   103,   106,   116,   116,   116,   116,   116,   116,   120,   120,
   124,   124,     0,   128,     0,     0,     0,     0,    83,     0,
     0,    64,    65,     0,     0,    13,     0,    32,     0,    41,
    44,     4,    37,   100,   102,   105,   114,   115,   110,   111,
   112,   113,   118,   119,   122,   123,   132,    76,     0,     0,
     0,     0,     0,     0,    15,    16,    31,    43,    42,     0,
    99,     0,    74,    70,    78,    82,    88,     0,    94,   158,
     0,    12,    14,    38,     0,    81,    71,    77,     0,    86,
    90,     0,    89,    96,    92,     0,   156,     0,     0,    10,
     0,     0,    79,    87,     0,    93,    94,   158,    97,     0,
    76,    81,    91,    95,   157,     0,    75,    80,    11,     0,
     0,     0
};

static const short yydefgoto[] = {   310,
    48,    10,    11,    72,   290,   182,   226,   183,    12,    73,
   128,    13,    83,    84,   133,   130,   187,    14,    15,    16,
    17,    18,    91,    92,   230,    49,    50,    51,   121,   124,
    52,    53,    54,    55,    56,    57,   170,   171,   172,   263,
   277,   278,   293,    58,    59,    60,    61,   280,    62,   283,
   268,   285,   296,   269,   139,   198,   140,   148,   103,   150,
   104,   105,   157,   106,   160,   107,   163,   108,   168,   109,
   165,    20,    30,    74,    85,   110,    87,    97,   143,   271,
   287
};

static const short yypact[] = {     2,
     3,   -12,   197,    16,    16,    34,    16,    38,    40,    47,
     5,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    19,    -4,
-32768,    30,    25,    26,    37,   180,-32768,   197,    76,-32768,
    23,    17,   165,     1,     1,-32768,   -37,    41,    84,    44,
    51,   180,    58,    60,-32768,    62,    66,-32768,    85,    71,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   -35,-32768,    19,-32768,-32768,-32768,-32768,-32768,
    72,-32768,-32768,    75,-32768,-32768,-32768,-32768,   106,-32768,
    16,-32768,-32768,-32768,-32768,    87,-32768,    77,    78,   121,
    81,-32768,    88,    41,    64,   144,-32768,    41,   105,-32768,
-32768,-32768,   117,   119,-32768,   112,   -21,    -6,   136,   120,
-32768,   156,    41,   139,    41,    41,    41,    41,-32768,   180,
-32768,    41,   180,-32768,-32768,    48,    41,-32768,   129,   153,
   126,    48,-32768,    41,   165,   127,   132,   197,   131,   130,
-32768,   137,-32768,-32768,   138,-32768,    41,-32768,    41,-32768,
   105,   105,   105,   105,   105,   105,-32768,   105,   105,-32768,
   105,   105,-32768,    41,-32768,-32768,    48,-32768,   141,   142,
   146,-32768,   143,    41,   145,   147,   152,   157,-32768,-32768,
-32768,   162,   135,   175,-32768,   106,-32768,-32768,-32768,-32768,
-32768,   174,   165,   165,    47,-32768,    41,-32768,-32768,-32768,
   117,   119,   112,   112,   112,   112,   112,   112,   -21,   -21,
    -6,    -6,   166,-32768,    41,   204,    41,   207,-32768,   205,
   201,-32768,-32768,   220,    48,-32768,    48,   129,     1,-32768,
   174,   197,-32768,   130,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   183,   180,   190,
   180,   180,    48,   165,   135,-32768,-32768,-32768,-32768,    47,
-32768,   233,-32768,-32768,   180,-32768,   210,    -3,   206,   195,
   200,   209,-32768,-32768,   211,   203,-32768,-32768,   180,-32768,
-32768,   180,-32768,    48,-32768,    48,-32768,   180,   212,-32768,
    41,   180,-32768,-32768,   247,-32768,   206,   195,-32768,    41,
   183,   203,-32768,-32768,-32768,   213,-32768,-32768,-32768,   268,
   270,-32768
};

static const short yypgoto[] = {-32768,
    -9,   -20,-32768,   239,-32768,-32768,    18,    49,   -70,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,    50,-32768,-32768,-32768,
-32768,-32768,   237,    46,    45,-32768,  -117,   -38,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   -24,
-32768,-32768,   -23,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   -17,-32768,    -2,   -90,    52,   -36,    80,   140,    82,
   134,   186,   -57,    94,  -149,   -93,  -137,   -72,-32768,-32768,
-32768,     6,   223,   -30,-32768,   -25,   -26,-32768,-32768,-32768,
    -8
};


#define	YYLAST		290


static const short yytable[] = {    63,
    27,   102,    88,   114,   142,   181,    86,    64,   129,    89,
    21,     2,    23,   281,    94,    63,     1,    95,   122,    75,
    76,    77,   123,    78,    19,    37,   177,   178,    96,   282,
    71,    66,    67,    68,    69,    70,    71,    79,     3,    90,
   158,   159,    22,    75,    76,    77,    24,    78,    25,    37,
    75,    76,    77,    31,    78,    28,    37,   161,   162,   243,
   244,   145,    26,    80,   209,   210,    75,    76,    77,   144,
    78,    81,    37,   245,   246,    29,   173,    32,   175,   176,
    34,   179,    33,   166,    65,   180,   131,    80,   211,   212,
   185,    35,   111,    63,    80,    98,    63,   191,   112,    99,
   184,   119,   100,   101,   192,   113,   190,    75,    76,    77,
    80,    78,   115,    37,   116,   228,   117,   195,    98,   141,
   118,   120,    99,   126,     4,   100,   101,   213,   127,   136,
   134,   264,   132,   266,   267,   135,   137,   219,    75,    76,
    77,   214,    78,   138,    37,   237,   238,   239,   240,   241,
   242,    80,    37,   151,   152,   153,   154,   147,   149,    98,
   234,   294,   231,   232,   169,   167,   100,   101,   174,   188,
   299,   155,   156,    66,    67,    68,    69,    70,   248,   186,
   250,   189,    80,   196,   193,   233,   197,    36,    37,   194,
   164,   225,   199,   200,   215,    26,   217,   216,   218,   184,
   220,   256,   221,    38,    39,    40,    41,   222,    42,   306,
    43,   260,   223,    44,   224,     4,     5,    45,     6,     7,
   227,   247,    63,   272,    63,    63,   276,   270,    46,    47,
   229,   249,     8,     9,   251,   253,   252,   254,    63,   262,
   265,   275,   279,   295,   203,   204,   205,   206,   207,   208,
   274,   286,    63,   302,   301,    63,   284,   288,   270,   292,
   298,    63,   289,   303,   291,    63,   300,   311,   309,   312,
    82,    93,   273,   255,   258,   259,   307,   257,   308,   304,
   235,   297,   202,   236,   146,   261,   201,   125,     0,   305
};

static const short yycheck[] = {    26,
    10,    38,    33,    42,    95,   123,    32,    28,    79,     9,
     5,     9,     7,    17,    52,    42,    15,    55,    54,     3,
     4,     5,    58,     7,     9,     9,   117,   118,    66,    33,
    14,     9,    10,    11,    12,    13,    14,    21,    51,    39,
    62,    63,     9,     3,     4,     5,     9,     7,     9,     9,
     3,     4,     5,    58,     7,    51,     9,    64,    65,   209,
   210,    98,    16,    47,   158,   159,     3,     4,     5,    96,
     7,    55,     9,   211,   212,    57,   113,    48,   115,   116,
    55,   120,    58,   109,     9,   122,    81,    47,   161,   162,
   127,    55,     9,   120,    47,    55,   123,   134,    55,    59,
   126,    17,    62,    63,   135,    55,   132,     3,     4,     5,
    47,     7,    55,     9,    55,   186,    55,   138,    55,    56,
    55,    51,    59,    52,    19,    62,    63,   164,    54,     9,
    54,   249,    46,   251,   252,    58,    56,   174,     3,     4,
     5,   167,     7,    56,     9,   203,   204,   205,   206,   207,
   208,    47,     9,    42,    43,    44,    45,    41,    40,    55,
   197,   279,   193,   194,     9,    46,    62,    63,    30,    17,
   288,    60,    61,     9,    10,    11,    12,    13,   215,    51,
   217,    56,    47,    53,    58,   195,    57,     8,     9,    58,
    55,    57,    56,    56,    54,    16,    51,    56,    56,   225,
    56,   227,    56,    24,    25,    26,    27,    56,    29,   300,
    31,   232,    56,    34,    53,    19,    20,    38,    22,    23,
    46,    56,   249,   254,   251,   252,   265,   253,    49,    50,
    57,    28,    36,    37,    28,    35,    32,    18,   265,    57,
    51,     9,    33,   282,   151,   152,   153,   154,   155,   156,
   260,    57,   279,   292,   291,   282,    51,    58,   284,    57,
   286,   288,    54,    17,    54,   292,    55,     0,    56,     0,
    32,    35,   255,   225,   229,   231,   301,   228,   302,   297,
   201,   284,   149,   202,    99,   234,   147,    65,    -1,   298
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 25 "yacc_syntax.y"
{printf("program -> 'prog' ID ';' prevdec block\n"); success();;
    break;}
case 2:
#line 28 "yacc_syntax.y"
{printf("block -> 'inicio' prevcommand 'fim'\n");;
    break;}
case 3:
#line 31 "yacc_syntax.y"
{printf("prevdec -> declaration ';' prevdec\n");;
    break;}
case 4:
#line 32 "yacc_syntax.y"
{printf("prevdec -> LAMBDA\n");;
    break;}
case 5:
#line 35 "yacc_syntax.y"
{printf("declaration -> vardec\n");;
    break;}
case 6:
#line 36 "yacc_syntax.y"
{printf("declaration -> usertype\n");;
    break;}
case 7:
#line 37 "yacc_syntax.y"
{printf("declaration -> labeldec\n");;
    break;}
case 8:
#line 38 "yacc_syntax.y"
{printf("declaration -> constdec\n");;
    break;}
case 9:
#line 39 "yacc_syntax.y"
{printf("declaration -> abstractiondec\n");;
    break;}
case 10:
#line 42 "yacc_syntax.y"
{printf("arraydec -> 'vetor' '[' rangelist ']' 'de' type arraydecaux\n");;
    break;}
case 11:
#line 45 "yacc_syntax.y"
{printf("arraydecaux -> '=' '(' expressionlist ')'\n");;
    break;}
case 12:
#line 46 "yacc_syntax.y"
{printf("arraydecaux -> LAMBDA\n");;
    break;}
case 13:
#line 49 "yacc_syntax.y"
{printf("rangelist -> range rangelistaux\n");;
    break;}
case 14:
#line 52 "yacc_syntax.y"
{printf("rangelistaux -> ',' range rangelistaux\n");;
    break;}
case 15:
#line 53 "yacc_syntax.y"
{printf("rangelistaux -> LAMBDA\n");;
    break;}
case 16:
#line 56 "yacc_syntax.y"
{printf("range -> atomic '..' atomic\n");;
    break;}
case 17:
#line 59 "yacc_syntax.y"
{printf("vardec -> 'var' idlist ':' varconstruction\n");;
    break;}
case 18:
#line 62 "yacc_syntax.y"
{printf("varconstruction -> type decwithassign\n");;
    break;}
case 19:
#line 63 "yacc_syntax.y"
{printf("varconstruction -> arraydec\n");;
    break;}
case 20:
#line 66 "yacc_syntax.y"
{printf("decwithassign -> '=' expr\n");;
    break;}
case 21:
#line 67 "yacc_syntax.y"
{printf("decwithassign -> LAMBDA\n");;
    break;}
case 22:
#line 70 "yacc_syntax.y"
{printf("usertype -> 'tipo' ID ':=' typedec\n");;
    break;}
case 23:
#line 73 "yacc_syntax.y"
{printf("typedec -> arraydec\n");;
    break;}
case 24:
#line 74 "yacc_syntax.y"
{printf("typedec -> typedecaux\n");;
    break;}
case 25:
#line 77 "yacc_syntax.y"
{printf("typedecaux -> 'registro' vardeclist 'fim'\n");;
    break;}
case 26:
#line 78 "yacc_syntax.y"
{printf("typedecaux -> atomic typedecauxrange\n");;
    break;}
case 27:
#line 79 "yacc_syntax.y"
{printf("typedecaux -> '(' idlist ')'\n");;
    break;}
case 28:
#line 82 "yacc_syntax.y"
{printf("typedecauxrange -> '..' atomic \n");;
    break;}
case 29:
#line 83 "yacc_syntax.y"
{printf("typedecauxrange -> LAMBDA\n");;
    break;}
case 30:
#line 86 "yacc_syntax.y"
{printf("vardeclist -> vardec vardeclistaux\n");;
    break;}
case 31:
#line 89 "yacc_syntax.y"
{printf("vardeclistaux -> ';' vardec vardeclistaux\n");;
    break;}
case 32:
#line 90 "yacc_syntax.y"
{printf("vardeclistaux -> LAMBDA\n");;
    break;}
case 33:
#line 93 "yacc_syntax.y"
{printf("labeldec -> 'rotulo' idlist\n");;
    break;}
case 34:
#line 96 "yacc_syntax.y"
{printf("constdec -> 'const' idlist ':' type '=' expr\n");;
    break;}
case 35:
#line 99 "yacc_syntax.y"
{printf("abstractiondec -> procdec\n");;
    break;}
case 36:
#line 100 "yacc_syntax.y"
{printf("abstractiondec -> funcdec\n");;
    break;}
case 37:
#line 103 "yacc_syntax.y"
{printf("procdec -> 'proc' ID '(' parameters ')' prevdec block\n");;
    break;}
case 38:
#line 106 "yacc_syntax.y"
{printf("funcdec -> 'func' ID '(' parameters ')' ':' type prevdec block\n");;
    break;}
case 39:
#line 109 "yacc_syntax.y"
{printf("parameters -> paramsaux\n");;
    break;}
case 40:
#line 110 "yacc_syntax.y"
{printf("parameters -> LAMBDA\n");;
    break;}
case 41:
#line 113 "yacc_syntax.y"
{printf("paramsaux -> ID ':' type paramslist\n");;
    break;}
case 42:
#line 114 "yacc_syntax.y"
{printf("paramsaux -> 'ref' ID ':' type paramslist\n");;
    break;}
case 43:
#line 117 "yacc_syntax.y"
{printf("paramslist -> paramsaux\n");;
    break;}
case 44:
#line 118 "yacc_syntax.y"
{printf("paramslist -> LAMBDA\n");;
    break;}
case 45:
#line 122 "yacc_syntax.y"
{printf("prevcommand -> commands\n");;
    break;}
case 46:
#line 123 "yacc_syntax.y"
{printf("prevcommand -> LAMBDA\n");;
    break;}
case 47:
#line 126 "yacc_syntax.y"
{printf("callcommand -> 'pare'\n");;
    break;}
case 48:
#line 127 "yacc_syntax.y"
{printf("callcommand -> write\n");;
    break;}
case 49:
#line 128 "yacc_syntax.y"
{printf("callcommand -> read\n");;
    break;}
case 50:
#line 129 "yacc_syntax.y"
{printf("callcommand -> loop\n");;
    break;}
case 51:
#line 130 "yacc_syntax.y"
{printf("callcommand -> block\n");;
    break;}
case 52:
#line 131 "yacc_syntax.y"
{printf("callcommand -> return\n");;
    break;}
case 53:
#line 132 "yacc_syntax.y"
{printf("callcommand -> 'continue'\n");;
    break;}
case 54:
#line 133 "yacc_syntax.y"
{printf("callcommand -> id callidbegin\n");;
    break;}
case 55:
#line 134 "yacc_syntax.y"
{printf("callcommand -> calllabel\n");;
    break;}
case 56:
#line 135 "yacc_syntax.y"
{printf("callcommand -> conditional\n");;
    break;}
case 57:
#line 138 "yacc_syntax.y"
{printf("commands -> callcommand commandsaux\n");;
    break;}
case 58:
#line 141 "yacc_syntax.y"
{printf("commandsaux -> ';' commands\n");;
    break;}
case 59:
#line 142 "yacc_syntax.y"
{printf("commandsaux -> LAMBDA\n");;
    break;}
case 60:
#line 145 "yacc_syntax.y"
{printf("callidbegin -> ':' callcommand \n");;
    break;}
case 61:
#line 146 "yacc_syntax.y"
{printf("callidbegin -> '=' expr\n");;
    break;}
case 62:
#line 147 "yacc_syntax.y"
{printf("callidbegin -> LAMBDA\n");;
    break;}
case 63:
#line 150 "yacc_syntax.y"
{printf("calllabel -> JUMP ID\n");;
    break;}
case 64:
#line 153 "yacc_syntax.y"
{printf("write -> 'escreva' '(' expressionlist ')'\n");;
    break;}
case 65:
#line 156 "yacc_syntax.y"
{printf("read -> 'leia' '(' expressionlist ')'\n");;
    break;}
case 66:
#line 159 "yacc_syntax.y"
{printf("return -> 'retorne' expr \n");;
    break;}
case 67:
#line 162 "yacc_syntax.y"
{printf("loop -> forloop\n");;
    break;}
case 68:
#line 163 "yacc_syntax.y"
{printf("loop -> whileloop\n");;
    break;}
case 69:
#line 164 "yacc_syntax.y"
{printf("loop -> repeatloop\n");;
    break;}
case 70:
#line 167 "yacc_syntax.y"
{printf("forloop -> 'para' '(' forstruct ')' 'faca' callcommand\n");;
    break;}
case 71:
#line 170 "yacc_syntax.y"
{printf("forstruct -> prevfor ';' expr ';' posfor \n");;
    break;}
case 72:
#line 173 "yacc_syntax.y"
{printf("prevfor -> varassignlist\n");;
    break;}
case 73:
#line 174 "yacc_syntax.y"
{printf("prevfor -> LAMBDA\n");;
    break;}
case 74:
#line 177 "yacc_syntax.y"
{printf("varassignlist -> ID '=' expr varassignlistaux\n");;
    break;}
case 75:
#line 180 "yacc_syntax.y"
{printf("varassignlistaux -> ',' ID '=' expr varassignlistaux\n");;
    break;}
case 76:
#line 181 "yacc_syntax.y"
{printf("varassignlistaux -> LAMBDA\n");;
    break;}
case 77:
#line 184 "yacc_syntax.y"
{printf("posfor -> posforaux\n");;
    break;}
case 78:
#line 185 "yacc_syntax.y"
{printf("posfor -> LAMBDA\n");;
    break;}
case 79:
#line 188 "yacc_syntax.y"
{printf("posforaux -> commands posforaux2\n");;
    break;}
case 80:
#line 191 "yacc_syntax.y"
{printf("posforaux2 -> ',' commands posforaux2\n");;
    break;}
case 81:
#line 192 "yacc_syntax.y"
{printf("posforaux2 -> LAMBDA\n");;
    break;}
case 82:
#line 195 "yacc_syntax.y"
{printf("whileloop -> 'enquanto' '(' expr ')' 'faca' callcommand\n");;
    break;}
case 83:
#line 198 "yacc_syntax.y"
{printf("repeatloop -> 'repita' commands 'ate' expr \n");;
    break;}
case 84:
#line 201 "yacc_syntax.y"
{printf("conditional -> ifcond\n");;
    break;}
case 85:
#line 202 "yacc_syntax.y"
{printf("conditional -> casecond\n");;
    break;}
case 86:
#line 205 "yacc_syntax.y"
{printf("ifcond -> 'se' '(' expr ')' 'entao' callcommand ifcondaux\n");;
    break;}
case 87:
#line 208 "yacc_syntax.y"
{printf("ifcondaux -> 'senao' callcommand \n");;
    break;}
case 88:
#line 209 "yacc_syntax.y"
{printf("ifcondaux -> LAMBDA \n");;
    break;}
case 89:
#line 213 "yacc_syntax.y"
{printf("casecond -> 'caso' '(' expr ')' 'seja' caselist casecondaux\n");;
    break;}
case 90:
#line 216 "yacc_syntax.y"
{printf("casecondaux -> 'fim'\n");;
    break;}
case 91:
#line 217 "yacc_syntax.y"
{printf("casecondaux -> 'senao' commands 'fim'\n");;
    break;}
case 92:
#line 220 "yacc_syntax.y"
{printf("caselist -> caseclause caselistaux\n");;
    break;}
case 93:
#line 223 "yacc_syntax.y"
{printf("caselistaux -> ';' caselistaux2\n");;
    break;}
case 94:
#line 224 "yacc_syntax.y"
{printf("caselistaux -> LAMBDA\n");;
    break;}
case 95:
#line 227 "yacc_syntax.y"
{printf("caselistaux2 -> caseclause caselistaux\n");;
    break;}
case 96:
#line 228 "yacc_syntax.y"
{printf("caselistaux2 -> LAMBDA\n");;
    break;}
case 97:
#line 231 "yacc_syntax.y"
{printf("caseclause -> atomiclist ':' callcommand\n");;
    break;}
case 98:
#line 234 "yacc_syntax.y"
{printf("expressionlist -> expr expressionlistaux\n");;
    break;}
case 99:
#line 237 "yacc_syntax.y"
{printf("expressionlistaux -> ',' expr expressionlistaux\n");;
    break;}
case 100:
#line 238 "yacc_syntax.y"
{printf("expressionlistaux -> LAMBDA\n");;
    break;}
case 101:
#line 241 "yacc_syntax.y"
{printf("expr -> andfact orfact\n");;
    break;}
case 102:
#line 244 "yacc_syntax.y"
{printf("orfact -> OR andfact orfact\n");;
    break;}
case 103:
#line 245 "yacc_syntax.y"
{printf("orfact -> LAMBDA\n");;
    break;}
case 104:
#line 248 "yacc_syntax.y"
{printf("andfact -> notfact andfactaux\n");;
    break;}
case 105:
#line 251 "yacc_syntax.y"
{printf("andfactaux -> AND notfact andfactaux\n");;
    break;}
case 106:
#line 252 "yacc_syntax.y"
{printf("andfactaux -> LAMBDA\n");;
    break;}
case 107:
#line 255 "yacc_syntax.y"
{printf("notfact -> '!' expreq\n");;
    break;}
case 108:
#line 256 "yacc_syntax.y"
{printf("notfact -> expreq\n");;
    break;}
case 109:
#line 259 "yacc_syntax.y"
{printf("expreq -> numericexpr expreqaux\n");;
    break;}
case 110:
#line 262 "yacc_syntax.y"
{printf("expreqaux -> EQUAL numericexpr expreqaux\n");;
    break;}
case 111:
#line 263 "yacc_syntax.y"
{printf("expreqaux -> NOTEQ numericexpr expreqaux\n");;
    break;}
case 112:
#line 264 "yacc_syntax.y"
{printf("expreqaux -> '>' numericexpr expreqaux\n");;
    break;}
case 113:
#line 265 "yacc_syntax.y"
{printf("expreqaux -> '<' numericexpr expreqaux\n");;
    break;}
case 114:
#line 266 "yacc_syntax.y"
{printf("expreqaux -> LESSEQ numericexpr expreqaux\n");;
    break;}
case 115:
#line 267 "yacc_syntax.y"
{printf("expreqaux -> GREATEQ numericexpr expreqaux\n");;
    break;}
case 116:
#line 268 "yacc_syntax.y"
{printf("expreqaux -> LAMBDA\n");;
    break;}
case 117:
#line 271 "yacc_syntax.y"
{printf("numericexpr -> exprmul exprsum\n");;
    break;}
case 118:
#line 274 "yacc_syntax.y"
{printf("exprsum -> '+' exprmul exprsum\n");;
    break;}
case 119:
#line 275 "yacc_syntax.y"
{printf("exprsum -> '-' exprmul exprsum\n");;
    break;}
case 120:
#line 276 "yacc_syntax.y"
{printf("exprsum -> LAMBDA\n");;
    break;}
case 121:
#line 279 "yacc_syntax.y"
{printf("exprmul -> simpleexpr exprmulaux\n");;
    break;}
case 122:
#line 282 "yacc_syntax.y"
{printf("exprmulaux -> '*' simpleexpr exprmulaux\n");;
    break;}
case 123:
#line 283 "yacc_syntax.y"
{printf("exprmulaux -> '/' simpleexpr exprmulaux\n");;
    break;}
case 124:
#line 284 "yacc_syntax.y"
{printf("exprmulaux -> LAMBDA\n");;
    break;}
case 125:
#line 287 "yacc_syntax.y"
{printf("simpleexpr -> atomic optrange\n");;
    break;}
case 126:
#line 288 "yacc_syntax.y"
{printf("simpleexpr -> optunary optbracket\n");;
    break;}
case 127:
#line 289 "yacc_syntax.y"
{printf("simpleexpr -> '(' expr ')'\n");;
    break;}
case 128:
#line 292 "yacc_syntax.y"
{printf("optrange -> DOUBLEDOT atomic\n");;
    break;}
case 129:
#line 293 "yacc_syntax.y"
{printf("optrange -> LAMBDA\n");;
    break;}
case 130:
#line 296 "yacc_syntax.y"
{printf("optunary -> '-'\n");;
    break;}
case 131:
#line 297 "yacc_syntax.y"
{printf("optunary -> '+'\n");;
    break;}
case 132:
#line 300 "yacc_syntax.y"
{printf("optbracket -> '(' expr ')'\n");;
    break;}
case 133:
#line 301 "yacc_syntax.y"
{printf("optbracket -> atomic\n");;
    break;}
case 134:
#line 304 "yacc_syntax.y"
{printf("idlist -> ID idlistaux\n");;
    break;}
case 135:
#line 307 "yacc_syntax.y"
{printf("idlistaux -> ',' ID idlistaux\n");;
    break;}
case 136:
#line 308 "yacc_syntax.y"
{printf("idlistaux -> LAMBDA\n");;
    break;}
case 137:
#line 311 "yacc_syntax.y"
{printf("type -> INT\n");;
    break;}
case 138:
#line 312 "yacc_syntax.y"
{printf("type -> REAL\n");;
    break;}
case 139:
#line 313 "yacc_syntax.y"
{printf("type -> BOOL\n");;
    break;}
case 140:
#line 314 "yacc_syntax.y"
{printf("type -> STRING\n");;
    break;}
case 141:
#line 315 "yacc_syntax.y"
{printf("type -> ID\n");;
    break;}
case 142:
#line 318 "yacc_syntax.y"
{printf("literal -> INT_VALUE\n");;
    break;}
case 143:
#line 319 "yacc_syntax.y"
{printf("literal -> REAL_VALUE\n");;
    break;}
case 144:
#line 320 "yacc_syntax.y"
{printf("literal -> HEXA_VALUE\n");;
    break;}
case 145:
#line 321 "yacc_syntax.y"
{printf("literal -> BOOL_VALUE\n");;
    break;}
case 146:
#line 322 "yacc_syntax.y"
{printf("literal -> STRING_VALUE\n");;
    break;}
case 147:
#line 325 "yacc_syntax.y"
{printf("atomic -> literal\n");;
    break;}
case 148:
#line 326 "yacc_syntax.y"
{printf("atomic -> id\n");;
    break;}
case 149:
#line 329 "yacc_syntax.y"
{printf("id -> ID idaux\n");;
    break;}
case 150:
#line 332 "yacc_syntax.y"
{printf("idaux -> '[' expressionlist ']'\n");;
    break;}
case 151:
#line 333 "yacc_syntax.y"
{printf("idaux -> '.' id\n");;
    break;}
case 152:
#line 334 "yacc_syntax.y"
{printf("idaux -> '(' idauxexpraux\n");;
    break;}
case 153:
#line 335 "yacc_syntax.y"
{printf("idaux -> LAMBDA\n");;
    break;}
case 154:
#line 338 "yacc_syntax.y"
{printf("idauxexpraux -> expressionlist ')'\n");;
    break;}
case 155:
#line 339 "yacc_syntax.y"
{printf("idauxexpraux -> ')'\n");;
    break;}
case 156:
#line 342 "yacc_syntax.y"
{printf("atomiclist -> atomic atomiclistaux\n");;
    break;}
case 157:
#line 345 "yacc_syntax.y"
{printf("atomiclistaux -> ',' atomic atomiclistaux\n");;
    break;}
case 158:
#line 346 "yacc_syntax.y"
{printf("atomiclistaux -> LAMBDA\n");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 349 "yacc_syntax.y"
                     /* C code */

void success() {
	printf("\033[0;32mparse success\033[0m\n"); 
	exit(1);
}

int main() {
	return yyparse();
}

void yyerror (char *s) {
	fprintf(stderr,"%s:", s);
	//fprintf(stderr,"Line: %d | Column: %d\n ", yylval.token->line, yylval.token->column);
	fprintf(stderr,"%d:%d: No expected '%s'\n", yylval.token->line, yylval.token->column, yylval.token->value);
}
