#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from yacc_syntax.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "yacc_syntax.y"

#include "../../token.c"
#include <stdio.h>     /* C declarations used in actions */
#include <stdlib.h>

void yyerror (char *s); 

int yylex();

void success();

#line 13 "yacc_syntax.y"
typedef union {Token* token;} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	HEXA_VALUE	258
#define	INT_VALUE	259
#define	REAL_VALUE	260
#define	FINAL	261
#define	BOOL_VALUE	262
#define	CONTINUE	263
#define	ID	264
#define	INT	265
#define	REAL	266
#define	BOOL	267
#define	STRING	268
#define	VECTOR	269
#define	PROG	270
#define	INIT	271
#define	END	272
#define	OF	273
#define	VAR	274
#define	LABEL	275
#define	STRUCT	276
#define	TYPE	277
#define	CONST	278
#define	RETURN	279
#define	JUMP	280
#define	FOR	281
#define	WHILE	282
#define	DO	283
#define	REPEAT	284
#define	UNTIL	285
#define	IF	286
#define	THEN	287
#define	ELSE	288
#define	CASE	289
#define	BE	290
#define	FUNC	291
#define	PROC	292
#define	BREAK	293
#define	REF	294
#define	AND	295
#define	OR	296
#define	LESSEQ	297
#define	GREATEQ	298
#define	EQUAL	299
#define	NOTEQ	300
#define	DOUBLEDOT	301
#define	STRING_VALUE	302
#define	CASSIGN	303
#define	WRITE	304
#define	READ	305
#define	INT_TYPE	306
#define	REAL_TYPE	307
#define	HEXA_TYPE	308
#define	STRING_TYPE	309


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int HEXA_VALUE;
static const int INT_VALUE;
static const int REAL_VALUE;
static const int FINAL;
static const int BOOL_VALUE;
static const int CONTINUE;
static const int ID;
static const int INT;
static const int REAL;
static const int BOOL;
static const int STRING;
static const int VECTOR;
static const int PROG;
static const int INIT;
static const int END;
static const int OF;
static const int VAR;
static const int LABEL;
static const int STRUCT;
static const int TYPE;
static const int CONST;
static const int RETURN;
static const int JUMP;
static const int FOR;
static const int WHILE;
static const int DO;
static const int REPEAT;
static const int UNTIL;
static const int IF;
static const int THEN;
static const int ELSE;
static const int CASE;
static const int BE;
static const int FUNC;
static const int PROC;
static const int BREAK;
static const int REF;
static const int AND;
static const int OR;
static const int LESSEQ;
static const int GREATEQ;
static const int EQUAL;
static const int NOTEQ;
static const int DOUBLEDOT;
static const int STRING_VALUE;
static const int CASSIGN;
static const int WRITE;
static const int READ;
static const int INT_TYPE;
static const int REAL_TYPE;
static const int HEXA_TYPE;
static const int STRING_TYPE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,HEXA_VALUE=258
	,INT_VALUE=259
	,REAL_VALUE=260
	,FINAL=261
	,BOOL_VALUE=262
	,CONTINUE=263
	,ID=264
	,INT=265
	,REAL=266
	,BOOL=267
	,STRING=268
	,VECTOR=269
	,PROG=270
	,INIT=271
	,END=272
	,OF=273
	,VAR=274
	,LABEL=275
	,STRUCT=276
	,TYPE=277
	,CONST=278
	,RETURN=279
	,JUMP=280
	,FOR=281
	,WHILE=282
	,DO=283
	,REPEAT=284
	,UNTIL=285
	,IF=286
	,THEN=287
	,ELSE=288
	,CASE=289
	,BE=290
	,FUNC=291
	,PROC=292
	,BREAK=293
	,REF=294
	,AND=295
	,OR=296
	,LESSEQ=297
	,GREATEQ=298
	,EQUAL=299
	,NOTEQ=300
	,DOUBLEDOT=301
	,STRING_VALUE=302
	,CASSIGN=303
	,WRITE=304
	,READ=305
	,INT_TYPE=306
	,REAL_TYPE=307
	,HEXA_TYPE=308
	,STRING_TYPE=309


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::HEXA_VALUE=258;
const int YY_parse_CLASS::INT_VALUE=259;
const int YY_parse_CLASS::REAL_VALUE=260;
const int YY_parse_CLASS::FINAL=261;
const int YY_parse_CLASS::BOOL_VALUE=262;
const int YY_parse_CLASS::CONTINUE=263;
const int YY_parse_CLASS::ID=264;
const int YY_parse_CLASS::INT=265;
const int YY_parse_CLASS::REAL=266;
const int YY_parse_CLASS::BOOL=267;
const int YY_parse_CLASS::STRING=268;
const int YY_parse_CLASS::VECTOR=269;
const int YY_parse_CLASS::PROG=270;
const int YY_parse_CLASS::INIT=271;
const int YY_parse_CLASS::END=272;
const int YY_parse_CLASS::OF=273;
const int YY_parse_CLASS::VAR=274;
const int YY_parse_CLASS::LABEL=275;
const int YY_parse_CLASS::STRUCT=276;
const int YY_parse_CLASS::TYPE=277;
const int YY_parse_CLASS::CONST=278;
const int YY_parse_CLASS::RETURN=279;
const int YY_parse_CLASS::JUMP=280;
const int YY_parse_CLASS::FOR=281;
const int YY_parse_CLASS::WHILE=282;
const int YY_parse_CLASS::DO=283;
const int YY_parse_CLASS::REPEAT=284;
const int YY_parse_CLASS::UNTIL=285;
const int YY_parse_CLASS::IF=286;
const int YY_parse_CLASS::THEN=287;
const int YY_parse_CLASS::ELSE=288;
const int YY_parse_CLASS::CASE=289;
const int YY_parse_CLASS::BE=290;
const int YY_parse_CLASS::FUNC=291;
const int YY_parse_CLASS::PROC=292;
const int YY_parse_CLASS::BREAK=293;
const int YY_parse_CLASS::REF=294;
const int YY_parse_CLASS::AND=295;
const int YY_parse_CLASS::OR=296;
const int YY_parse_CLASS::LESSEQ=297;
const int YY_parse_CLASS::GREATEQ=298;
const int YY_parse_CLASS::EQUAL=299;
const int YY_parse_CLASS::NOTEQ=300;
const int YY_parse_CLASS::DOUBLEDOT=301;
const int YY_parse_CLASS::STRING_VALUE=302;
const int YY_parse_CLASS::CASSIGN=303;
const int YY_parse_CLASS::WRITE=304;
const int YY_parse_CLASS::READ=305;
const int YY_parse_CLASS::INT_TYPE=306;
const int YY_parse_CLASS::REAL_TYPE=307;
const int YY_parse_CLASS::HEXA_TYPE=308;
const int YY_parse_CLASS::STRING_TYPE=309;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		308
#define	YYFLAG		-32768
#define	YYNTBASE	71

#define YYTRANSLATE(x) ((unsigned)(x) <= 309 ? yytranslate[x] : 152)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    63,     2,     2,     2,     2,     2,     2,    59,
    60,    68,    66,    61,    67,    70,    69,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    62,    55,    65,
    58,    64,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    56,     2,    57,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     6,    10,    14,    15,    17,    19,    21,    23,    25,
    33,    38,    39,    42,    46,    47,    51,    56,    59,    61,
    64,    65,    70,    72,    74,    78,    81,    85,    88,    89,
    92,    96,    97,   100,   105,   107,   109,   117,   127,   129,
   130,   135,   141,   144,   145,   147,   148,   150,   152,   154,
   156,   158,   160,   162,   165,   167,   169,   172,   175,   176,
   179,   182,   183,   186,   191,   196,   199,   201,   203,   205,
   212,   218,   220,   221,   226,   232,   233,   235,   236,   239,
   243,   244,   251,   256,   258,   260,   268,   271,   272,   280,
   282,   286,   289,   292,   293,   296,   297,   301,   304,   308,
   309,   312,   316,   317,   320,   324,   325,   328,   330,   333,
   337,   341,   345,   349,   353,   357,   358,   361,   365,   369,
   370,   373,   377,   381,   382,   385,   388,   392,   395,   396,
   398,   400,   404,   406,   409,   413,   414,   416,   418,   420,
   422,   424,   426,   428,   430,   432,   434,   436,   438,   441,
   445,   448,   452,   453,   456,   460
};

static const short yyrhs[] = {    15,
     9,    55,    73,    72,     0,    16,    97,    17,     0,    74,
    55,    73,     0,     0,    80,     0,    83,     0,    89,     0,
    90,     0,    91,     0,    14,    56,    77,    57,    18,   145,
    76,     0,    58,    59,   126,    60,     0,     0,    79,    78,
     0,    61,    79,    78,     0,     0,   147,    46,   147,     0,
    19,   143,    62,    81,     0,   145,    82,     0,    75,     0,
    58,   128,     0,     0,    22,     9,    48,    84,     0,    75,
     0,    85,     0,    21,    87,    17,     0,   147,    86,     0,
    59,   143,    60,     0,    46,   147,     0,     0,    80,    88,
     0,    55,    80,    88,     0,     0,    20,   143,     0,    23,
     9,    58,   128,     0,    92,     0,    93,     0,    37,     9,
    59,    94,    60,    73,    72,     0,    36,     9,    59,    94,
    60,    62,   145,    73,    72,     0,    95,     0,     0,     9,
    62,   145,    96,     0,    39,     9,    62,   145,    96,     0,
    61,    95,     0,     0,    99,     0,     0,    38,     0,   103,
     0,   104,     0,   106,     0,    72,     0,   105,     0,     8,
     0,   148,   101,     0,   102,     0,   117,     0,    98,   100,
     0,    55,    99,     0,     0,    62,    98,     0,    58,   128,
     0,     0,    25,     9,     0,    49,    59,   126,    60,     0,
    50,    59,   126,    60,     0,    24,   128,     0,   107,     0,
   115,     0,   116,     0,    26,    59,   108,    60,    28,    98,
     0,   109,    55,   128,    55,   112,     0,   110,     0,     0,
     9,    58,   128,   111,     0,    61,     9,    58,   128,   111,
     0,     0,   113,     0,     0,    99,   114,     0,    61,    99,
   114,     0,     0,    27,    59,   128,    60,    28,    98,     0,
    29,    99,    30,   128,     0,   118,     0,   120,     0,    31,
    59,   128,    60,    32,    98,   119,     0,    33,    98,     0,
     0,    34,    59,   128,    60,    35,   122,   121,     0,    17,
     0,    33,    99,    17,     0,   125,   123,     0,    55,   124,
     0,     0,   125,   123,     0,     0,   150,    62,    98,     0,
   128,   127,     0,    61,   128,   127,     0,     0,   130,   129,
     0,    41,   130,   129,     0,     0,   132,   131,     0,    40,
   132,   131,     0,     0,    63,   133,     0,   133,     0,   135,
   134,     0,    44,   135,   134,     0,    45,   135,   134,     0,
    64,   135,   134,     0,    65,   135,   134,     0,    42,   135,
   134,     0,    43,   135,   134,     0,     0,   137,   136,     0,
    66,   137,   136,     0,    67,   137,   136,     0,     0,   139,
   138,     0,    68,   139,   138,     0,    69,   139,   138,     0,
     0,   147,   140,     0,   141,   142,     0,    59,   128,    60,
     0,    46,   147,     0,     0,    67,     0,    66,     0,    59,
   128,    60,     0,   147,     0,     9,   144,     0,    61,     9,
   144,     0,     0,    51,     0,    52,     0,    53,     0,    54,
     0,     9,     0,     4,     0,     5,     0,     3,     0,     7,
     0,    47,     0,   146,     0,   148,     0,     9,   149,     0,
    56,   126,    57,     0,    70,   148,     0,    59,   126,    60,
     0,     0,   147,   151,     0,    61,   147,   151,     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    26,    29,    32,    33,    36,    37,    38,    39,    40,    43,
    46,    47,    50,    53,    54,    57,    60,    63,    64,    67,
    68,    71,    74,    75,    78,    79,    80,    83,    84,    87,
    90,    91,    94,    97,   100,   101,   104,   107,   110,   111,
   114,   115,   118,   119,   123,   124,   127,   128,   129,   130,
   131,   132,   133,   134,   135,   136,   139,   142,   143,   146,
   147,   148,   151,   154,   157,   160,   163,   164,   165,   168,
   171,   174,   175,   178,   181,   182,   185,   186,   189,   192,
   193,   196,   199,   202,   203,   206,   209,   210,   214,   217,
   218,   221,   224,   225,   228,   229,   232,   235,   238,   239,
   242,   245,   246,   249,   252,   253,   256,   257,   260,   263,
   264,   265,   266,   267,   268,   269,   272,   275,   276,   277,
   280,   283,   284,   285,   288,   289,   290,   293,   294,   297,
   298,   301,   302,   305,   308,   309,   312,   313,   314,   315,
   316,   319,   320,   321,   322,   323,   326,   327,   330,   333,
   334,   335,   336,   339,   342,   343
};

static const char * const yytname[] = {   "$","error","$illegal.","HEXA_VALUE",
"INT_VALUE","REAL_VALUE","FINAL","BOOL_VALUE","CONTINUE","ID","INT","REAL","BOOL",
"STRING","VECTOR","PROG","INIT","END","OF","VAR","LABEL","STRUCT","TYPE","CONST",
"RETURN","JUMP","FOR","WHILE","DO","REPEAT","UNTIL","IF","THEN","ELSE","CASE",
"BE","FUNC","PROC","BREAK","REF","AND","OR","LESSEQ","GREATEQ","EQUAL","NOTEQ",
"DOUBLEDOT","STRING_VALUE","CASSIGN","WRITE","READ","INT_TYPE","REAL_TYPE","HEXA_TYPE",
"STRING_TYPE","';'","'['","']'","'='","'('","')'","','","':'","'!'","'>'","'<'",
"'+'","'-'","'*'","'/'","'.'","program","block","prevdec","declaration","arraydec",
"arraydecaux","rangelist","rangelistaux","range","vardec","varconstruction",
"decwithassign","usertype","typedec","typedecaux","typedecauxrange","vardeclist",
"vardeclistaux","labeldec","constdec","abstractiondec","procdec","funcdec","parameters",
"paramsaux","paramslist","prevcommand","callcommand","commands","commandsaux",
"callidbegin","calllabel","write","read","return","loop","forloop","forstruct",
"prevfor","varassignlist","varassignlistaux","posfor","posforaux","posforaux2",
"whileloop","repeatloop","conditional","ifcond","ifcondaux","casecond","casecondaux",
"caselist","caselistaux","caselistaux2","caseclause","expressionlist","expressionlistaux",
"expr","orfact","andfact","andfactaux","notfact","expreq","expreqaux","numericexpr",
"exprsum","exprmul","exprmulaux","simpleexpr","optrange","optunary","optbracket",
"idlist","idlistaux","type","literal","atomic","id","idaux","atomiclist","atomiclistaux",
""
};
#endif

static const short yyr1[] = {     0,
    71,    72,    73,    73,    74,    74,    74,    74,    74,    75,
    76,    76,    77,    78,    78,    79,    80,    81,    81,    82,
    82,    83,    84,    84,    85,    85,    85,    86,    86,    87,
    88,    88,    89,    90,    91,    91,    92,    93,    94,    94,
    95,    95,    96,    96,    97,    97,    98,    98,    98,    98,
    98,    98,    98,    98,    98,    98,    99,   100,   100,   101,
   101,   101,   102,   103,   104,   105,   106,   106,   106,   107,
   108,   109,   109,   110,   111,   111,   112,   112,   113,   114,
   114,   115,   116,   117,   117,   118,   119,   119,   120,   121,
   121,   122,   123,   123,   124,   124,   125,   126,   127,   127,
   128,   129,   129,   130,   131,   131,   132,   132,   133,   134,
   134,   134,   134,   134,   134,   134,   135,   136,   136,   136,
   137,   138,   138,   138,   139,   139,   139,   140,   140,   141,
   141,   142,   142,   143,   144,   144,   145,   145,   145,   145,
   145,   146,   146,   146,   146,   146,   147,   147,   148,   149,
   149,   149,   149,   150,   151,   151
};

static const short yyr2[] = {     0,
     5,     3,     3,     0,     1,     1,     1,     1,     1,     7,
     4,     0,     2,     3,     0,     3,     4,     2,     1,     2,
     0,     4,     1,     1,     3,     2,     3,     2,     0,     2,
     3,     0,     2,     4,     1,     1,     7,     9,     1,     0,
     4,     5,     2,     0,     1,     0,     1,     1,     1,     1,
     1,     1,     1,     2,     1,     1,     2,     2,     0,     2,
     2,     0,     2,     4,     4,     2,     1,     1,     1,     6,
     5,     1,     0,     4,     5,     0,     1,     0,     2,     3,
     0,     6,     4,     1,     1,     7,     2,     0,     7,     1,
     3,     2,     2,     0,     2,     0,     3,     2,     3,     0,
     2,     3,     0,     2,     3,     0,     2,     1,     2,     3,
     3,     3,     3,     3,     3,     0,     2,     3,     3,     0,
     2,     3,     3,     0,     2,     2,     3,     2,     0,     1,
     1,     3,     1,     2,     3,     0,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     2,     3,
     2,     3,     0,     2,     3,     0
};

static const short yydefact[] = {     0,
     0,     0,     4,     0,     0,     0,     0,     0,     0,     0,
     0,     5,     6,     7,     8,     9,    35,    36,   136,     0,
    33,     0,     0,     0,     0,    46,     1,     4,     0,   134,
     0,     0,     0,    40,    40,    53,   153,     0,     0,     0,
     0,     0,     0,     0,    47,     0,     0,    51,     0,    59,
    45,    55,    48,    49,    52,    50,    67,    68,    69,    56,
    84,    85,    62,     3,   136,   141,     0,   137,   138,   139,
   140,    19,    17,    21,   144,   142,   143,   145,     0,   146,
     0,    23,    22,    24,   147,    29,   148,     0,     0,   131,
   130,    34,   103,   106,   108,   116,   120,   124,     0,   129,
     0,     0,     0,    39,     0,     0,     0,     0,   149,    66,
    63,    73,     0,     0,     0,     0,     0,     0,     2,     0,
    57,     0,     0,    54,   135,     0,     0,    18,    32,     0,
     0,     0,    26,     0,   107,     0,   101,     0,   104,     0,
     0,     0,     0,     0,     0,   109,     0,     0,   117,     0,
     0,   121,     0,   126,   133,     0,   125,     0,     0,     0,
     4,     0,   100,     0,   151,     0,     0,     0,    72,     0,
     0,     0,     0,     0,     0,    58,    61,    60,     0,    15,
     0,    20,     0,    30,    25,    27,    28,   127,   103,   106,
   116,   116,   116,   116,   116,   116,   120,   120,   124,   124,
     0,   128,    44,     0,     0,     0,   150,     0,    98,   152,
     0,     0,     0,     0,    83,     0,     0,    64,    65,     0,
     0,    13,     0,    32,   102,   105,   114,   115,   110,   111,
   112,   113,   118,   119,   122,   123,   132,     0,    41,    44,
     4,    37,   100,    76,     0,     0,     0,     0,     0,     0,
    15,    16,    31,    43,    42,     0,    99,     0,    74,    70,
    78,    82,    88,     0,    94,   156,     0,    12,    14,    38,
     0,    81,    71,    77,     0,    86,    90,     0,    89,    96,
    92,     0,   154,     0,     0,    10,     0,     0,    79,    87,
     0,    93,    94,   156,    97,     0,    76,    81,    91,    95,
   155,     0,    75,    80,    11,     0,     0,     0
};

static const short yydefgoto[] = {   306,
    48,    10,    11,    72,   286,   179,   222,   180,    12,    73,
   128,    13,    83,    84,   133,   130,   184,    14,    15,    16,
    17,    18,   103,   104,   239,    49,    50,    51,   121,   124,
    52,    53,    54,    55,    56,    57,   167,   168,   169,   259,
   273,   274,   289,    58,    59,    60,    61,   276,    62,   279,
   264,   281,   292,   265,   162,   209,   163,   137,    93,   139,
    94,    95,   146,    96,   149,    97,   152,    98,   157,    99,
   154,    20,    30,    74,    85,   100,    87,   109,   267,   283
};

static const short yypact[] = {    11,
    19,   -21,    82,    34,    34,    40,    42,    55,    60,    75,
    57,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    35,    65,
-32768,    76,    67,    64,    71,   133,-32768,    82,   123,-32768,
     1,    18,    26,     8,     8,-32768,    61,    26,   125,    78,
    79,   133,    81,    95,-32768,    96,   102,-32768,   118,   111,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   -38,-32768,    35,-32768,   107,-32768,-32768,-32768,
-32768,-32768,-32768,   110,-32768,-32768,-32768,-32768,   150,-32768,
    34,-32768,-32768,-32768,-32768,   124,-32768,    26,    41,-32768,
-32768,-32768,   134,   137,-32768,   108,    -8,   -50,    63,   128,
   116,   171,   130,-32768,   132,    26,    26,   184,-32768,-32768,
-32768,   185,    26,   165,    26,    26,    26,    26,-32768,   133,
-32768,    26,   133,-32768,-32768,    33,    26,-32768,   141,   180,
   139,    33,-32768,   142,-32768,    26,-32768,    26,-32768,    41,
    41,    41,    41,    41,    41,-32768,    41,    41,-32768,    41,
    41,-32768,    26,-32768,-32768,    33,-32768,    62,   143,   144,
    82,   146,   147,   149,-32768,   152,   151,   157,-32768,   153,
    26,   154,   155,   158,   160,-32768,-32768,-32768,   166,   156,
   161,-32768,   150,-32768,-32768,-32768,-32768,-32768,   134,   137,
   108,   108,   108,   108,   108,   108,    -8,    -8,   -50,   -50,
   164,-32768,   167,    62,    62,    75,-32768,    26,-32768,-32768,
    26,   176,    26,   197,-32768,   198,   194,-32768,-32768,   213,
    33,-32768,    33,   141,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,     8,-32768,   167,
    82,-32768,   147,   172,   133,   177,   133,   133,    33,    62,
   156,-32768,-32768,-32768,-32768,    75,-32768,   225,-32768,-32768,
   133,-32768,   203,    24,   182,   178,   179,   187,-32768,-32768,
   188,   181,-32768,-32768,   133,-32768,-32768,   133,-32768,    33,
-32768,    33,-32768,   133,   189,-32768,    26,   133,-32768,-32768,
   221,-32768,   182,   178,-32768,    26,   172,   181,-32768,-32768,
-32768,   183,-32768,-32768,-32768,   240,   247,-32768
};

static const short yypgoto[] = {-32768,
    -5,   -25,-32768,   218,-32768,-32768,     2,    39,   -72,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,    32,-32768,-32768,-32768,
-32768,-32768,   226,    25,    27,-32768,  -119,   -34,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   -33,
-32768,-32768,   -30,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   -28,-32768,   -14,  -105,    28,   -32,    80,   136,    83,
   138,   186,   -48,    44,  -135,   -73,  -121,   -52,-32768,-32768,
-32768,     6,   205,  -144,-32768,   -23,   -26,-32768,-32768,   -20
};


#define	YYLAST		276


static const short yytable[] = {    63,
    92,   164,    64,   178,    27,   110,   129,   114,    86,    66,
    21,   174,   175,   203,    67,    63,   101,   150,   151,   122,
    75,    76,    77,   123,    78,     1,    37,     2,    75,    76,
    77,    67,    78,     3,    37,    75,    76,    77,    79,    78,
   277,    37,    19,    75,    76,    77,   102,    78,    22,    37,
    23,    68,    69,    70,    71,   134,   278,   147,   148,   240,
   241,   233,   234,    24,    80,    75,    76,    77,    25,    78,
    66,    37,    80,   197,   198,   155,    81,   235,   236,    80,
   170,   165,   172,   173,    88,   176,   131,    80,    89,   177,
    26,    90,    91,    63,   182,    29,    63,   199,   200,    88,
     4,     5,   181,     6,     7,   268,    90,    91,   187,    80,
   224,    28,    68,    69,    70,    71,   106,     8,     9,   107,
   201,   153,    34,    32,    33,   260,    31,   262,   263,    35,
   108,    65,   202,   111,   119,   206,   112,   113,   215,   115,
    36,    37,   227,   228,   229,   230,   231,   232,    26,   140,
   141,   142,   143,   116,   117,   290,    38,    39,    40,    41,
   118,    42,   126,    43,   295,   120,    44,   127,     4,   132,
    45,   144,   145,   156,   136,   243,   138,   158,   244,   159,
   246,    46,    47,   191,   192,   193,   194,   195,   196,   160,
   302,   161,    37,   166,   171,   183,   185,   181,   186,   252,
   242,   188,   207,   245,   204,   205,   223,   208,   210,   211,
   212,   213,   214,   216,   217,   256,   221,   218,    63,   219,
    63,    63,   220,   237,   247,   266,   272,   238,   249,   248,
   250,   261,   258,   271,    63,   275,   280,   299,   282,   307,
   284,   288,   305,   291,   285,   287,   308,   296,    63,    82,
   270,    63,   269,   298,   297,   253,   266,    63,   294,   251,
   105,    63,   254,   303,   300,   293,   255,   304,   225,   125,
   257,   189,   226,   301,   135,   190
};

static const short yycheck[] = {    26,
    33,   107,    28,   123,    10,    38,    79,    42,    32,     9,
     5,   117,   118,   158,    14,    42,     9,    68,    69,    58,
     3,     4,     5,    62,     7,    15,     9,     9,     3,     4,
     5,    14,     7,    55,     9,     3,     4,     5,    21,     7,
    17,     9,     9,     3,     4,     5,    39,     7,     9,     9,
     9,    51,    52,    53,    54,    88,    33,    66,    67,   204,
   205,   197,   198,     9,    47,     3,     4,     5,     9,     7,
     9,     9,    47,   147,   148,    99,    59,   199,   200,    47,
   113,   108,   115,   116,    59,   120,    81,    47,    63,   122,
    16,    66,    67,   120,   127,    61,   123,   150,   151,    59,
    19,    20,   126,    22,    23,   250,    66,    67,   132,    47,
   183,    55,    51,    52,    53,    54,    56,    36,    37,    59,
   153,    59,    59,    48,    58,   245,    62,   247,   248,    59,
    70,     9,   156,     9,    17,   161,    59,    59,   171,    59,
     8,     9,   191,   192,   193,   194,   195,   196,    16,    42,
    43,    44,    45,    59,    59,   275,    24,    25,    26,    27,
    59,    29,    56,    31,   284,    55,    34,    58,    19,    46,
    38,    64,    65,    46,    41,   208,    40,    62,   211,     9,
   213,    49,    50,   140,   141,   142,   143,   144,   145,    60,
   296,    60,     9,     9,    30,    55,    17,   221,    60,   223,
   206,    60,    57,    28,    62,    62,    46,    61,    60,    58,
    60,    55,    60,    60,    60,   241,    61,    60,   245,    60,
   247,   248,    57,    60,    28,   249,   261,    61,    35,    32,
    18,    55,    61,     9,   261,    33,    55,    17,    61,     0,
    62,    61,    60,   278,    58,    58,     0,    59,   275,    32,
   256,   278,   251,   288,   287,   224,   280,   284,   282,   221,
    35,   288,   238,   297,   293,   280,   240,   298,   189,    65,
   243,   136,   190,   294,    89,   138
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 26 "yacc_syntax.y"
{printf("program -> 'prog' ID ';' prevdec block\n"); success();;
    break;}
case 2:
#line 29 "yacc_syntax.y"
{printf("block -> 'inicio' prevcommand 'fim'\n");;
    break;}
case 3:
#line 32 "yacc_syntax.y"
{printf("prevdec -> declaration ';' prevdec\n");;
    break;}
case 4:
#line 33 "yacc_syntax.y"
{printf("prevdec -> LAMBDA\n");;
    break;}
case 5:
#line 36 "yacc_syntax.y"
{printf("declaration -> vardec\n");;
    break;}
case 6:
#line 37 "yacc_syntax.y"
{printf("declaration -> usertype\n");;
    break;}
case 7:
#line 38 "yacc_syntax.y"
{printf("declaration -> labeldec\n");;
    break;}
case 8:
#line 39 "yacc_syntax.y"
{printf("declaration -> constdec\n");;
    break;}
case 9:
#line 40 "yacc_syntax.y"
{printf("declaration -> abstractiondec\n");;
    break;}
case 10:
#line 43 "yacc_syntax.y"
{printf("arraydec -> 'vetor' '[' rangelist ']' 'de' type arraydecaux\n");;
    break;}
case 11:
#line 46 "yacc_syntax.y"
{printf("arraydecaux -> '=' '(' expressionlist ')'\n");;
    break;}
case 12:
#line 47 "yacc_syntax.y"
{printf("arraydecaux -> LAMBDA\n");;
    break;}
case 13:
#line 50 "yacc_syntax.y"
{printf("rangelist -> range rangelistaux\n");;
    break;}
case 14:
#line 53 "yacc_syntax.y"
{printf("rangelistaux -> ',' range rangelistaux\n");;
    break;}
case 15:
#line 54 "yacc_syntax.y"
{printf("rangelistaux -> LAMBDA\n");;
    break;}
case 16:
#line 57 "yacc_syntax.y"
{printf("range -> atomic '..' atomic\n");;
    break;}
case 17:
#line 60 "yacc_syntax.y"
{printf("vardec -> 'var' idlist ':' varconstruction\n");;
    break;}
case 18:
#line 63 "yacc_syntax.y"
{printf("varconstruction -> type decwithassign\n");;
    break;}
case 19:
#line 64 "yacc_syntax.y"
{printf("varconstruction -> arraydec\n");;
    break;}
case 20:
#line 67 "yacc_syntax.y"
{printf("decwithassign -> '=' expr\n");;
    break;}
case 21:
#line 68 "yacc_syntax.y"
{printf("decwithassign -> LAMBDA\n");;
    break;}
case 22:
#line 71 "yacc_syntax.y"
{printf("usertype -> 'tipo' ID ':=' typedec\n");;
    break;}
case 23:
#line 74 "yacc_syntax.y"
{printf("typedec -> arraydec\n");;
    break;}
case 24:
#line 75 "yacc_syntax.y"
{printf("typedec -> typedecaux\n");;
    break;}
case 25:
#line 78 "yacc_syntax.y"
{printf("typedecaux -> 'registro' vardeclist 'fim'\n");;
    break;}
case 26:
#line 79 "yacc_syntax.y"
{printf("typedecaux -> atomic typedecauxrange\n");;
    break;}
case 27:
#line 80 "yacc_syntax.y"
{printf("typedecaux -> '(' idlist ')'\n");;
    break;}
case 28:
#line 83 "yacc_syntax.y"
{printf("typedecauxrange -> '..' atomic \n");;
    break;}
case 29:
#line 84 "yacc_syntax.y"
{printf("typedecauxrange -> LAMBDA\n");;
    break;}
case 30:
#line 87 "yacc_syntax.y"
{printf("vardeclist -> vardec vardeclistaux\n");;
    break;}
case 31:
#line 90 "yacc_syntax.y"
{printf("vardeclistaux -> ';' vardec vardeclistaux\n");;
    break;}
case 32:
#line 91 "yacc_syntax.y"
{printf("vardeclistaux -> LAMBDA\n");;
    break;}
case 33:
#line 94 "yacc_syntax.y"
{printf("labeldec -> 'rotulo' idlist\n");;
    break;}
case 34:
#line 97 "yacc_syntax.y"
{printf("constdec -> 'const' ID '=' expr\n");;
    break;}
case 35:
#line 100 "yacc_syntax.y"
{printf("abstractiondec -> procdec\n");;
    break;}
case 36:
#line 101 "yacc_syntax.y"
{printf("abstractiondec -> funcdec\n");;
    break;}
case 37:
#line 104 "yacc_syntax.y"
{printf("procdec -> 'proc' ID '(' parameters ')' prevdec block\n");;
    break;}
case 38:
#line 107 "yacc_syntax.y"
{printf("funcdec -> 'func' ID '(' parameters ')' ':' type prevdec block\n");;
    break;}
case 39:
#line 110 "yacc_syntax.y"
{printf("parameters -> paramsaux\n");;
    break;}
case 40:
#line 111 "yacc_syntax.y"
{printf("parameters -> LAMBDA\n");;
    break;}
case 41:
#line 114 "yacc_syntax.y"
{printf("paramsaux -> ID ':' type paramslist\n");;
    break;}
case 42:
#line 115 "yacc_syntax.y"
{printf("paramsaux -> 'ref' ID ':' type paramslist\n");;
    break;}
case 43:
#line 118 "yacc_syntax.y"
{printf("paramslist -> paramsaux\n");;
    break;}
case 44:
#line 119 "yacc_syntax.y"
{printf("paramslist -> LAMBDA\n");;
    break;}
case 45:
#line 123 "yacc_syntax.y"
{printf("prevcommand -> commands\n");;
    break;}
case 46:
#line 124 "yacc_syntax.y"
{printf("prevcommand -> LAMBDA\n");;
    break;}
case 47:
#line 127 "yacc_syntax.y"
{printf("callcommand -> 'pare'\n");;
    break;}
case 48:
#line 128 "yacc_syntax.y"
{printf("callcommand -> write\n");;
    break;}
case 49:
#line 129 "yacc_syntax.y"
{printf("callcommand -> read\n");;
    break;}
case 50:
#line 130 "yacc_syntax.y"
{printf("callcommand -> loop\n");;
    break;}
case 51:
#line 131 "yacc_syntax.y"
{printf("callcommand -> block\n");;
    break;}
case 52:
#line 132 "yacc_syntax.y"
{printf("callcommand -> return\n");;
    break;}
case 53:
#line 133 "yacc_syntax.y"
{printf("callcommand -> 'continue'\n");;
    break;}
case 54:
#line 134 "yacc_syntax.y"
{printf("callcommand -> id callidbegin\n");;
    break;}
case 55:
#line 135 "yacc_syntax.y"
{printf("callcommand -> calllabel\n");;
    break;}
case 56:
#line 136 "yacc_syntax.y"
{printf("callcommand -> conditional\n");;
    break;}
case 57:
#line 139 "yacc_syntax.y"
{printf("commands -> callcommand commandsaux\n");;
    break;}
case 58:
#line 142 "yacc_syntax.y"
{printf("commandsaux -> ';' commands\n");;
    break;}
case 59:
#line 143 "yacc_syntax.y"
{printf("commandsaux -> LAMBDA\n");;
    break;}
case 60:
#line 146 "yacc_syntax.y"
{printf("callidbegin -> ':' callcommand \n");;
    break;}
case 61:
#line 147 "yacc_syntax.y"
{printf("callidbegin -> '=' expr\n");;
    break;}
case 62:
#line 148 "yacc_syntax.y"
{printf("callidbegin -> LAMBDA\n");;
    break;}
case 63:
#line 151 "yacc_syntax.y"
{printf("calllabel -> JUMP ID\n");;
    break;}
case 64:
#line 154 "yacc_syntax.y"
{printf("write -> 'escreva' '(' expressionlist ')'\n");;
    break;}
case 65:
#line 157 "yacc_syntax.y"
{printf("read -> 'leia' '(' expressionlist ')'\n");;
    break;}
case 66:
#line 160 "yacc_syntax.y"
{printf("return -> 'retorne' expr \n");;
    break;}
case 67:
#line 163 "yacc_syntax.y"
{printf("loop -> forloop\n");;
    break;}
case 68:
#line 164 "yacc_syntax.y"
{printf("loop -> whileloop\n");;
    break;}
case 69:
#line 165 "yacc_syntax.y"
{printf("loop -> repeatloop\n");;
    break;}
case 70:
#line 168 "yacc_syntax.y"
{printf("forloop -> 'para' '(' forstruct ')' 'faca' callcommand\n");;
    break;}
case 71:
#line 171 "yacc_syntax.y"
{printf("forstruct -> prevfor ';' expr ';' posfor \n");;
    break;}
case 72:
#line 174 "yacc_syntax.y"
{printf("prevfor -> varassignlist\n");;
    break;}
case 73:
#line 175 "yacc_syntax.y"
{printf("prevfor -> LAMBDA\n");;
    break;}
case 74:
#line 178 "yacc_syntax.y"
{printf("varassignlist -> ID '=' expr varassignlistaux\n");;
    break;}
case 75:
#line 181 "yacc_syntax.y"
{printf("varassignlistaux -> ',' ID '=' expr varassignlistaux\n");;
    break;}
case 76:
#line 182 "yacc_syntax.y"
{printf("varassignlistaux -> LAMBDA\n");;
    break;}
case 77:
#line 185 "yacc_syntax.y"
{printf("posfor -> posforaux\n");;
    break;}
case 78:
#line 186 "yacc_syntax.y"
{printf("posfor -> LAMBDA\n");;
    break;}
case 79:
#line 189 "yacc_syntax.y"
{printf("posforaux -> commands posforaux2\n");;
    break;}
case 80:
#line 192 "yacc_syntax.y"
{printf("posforaux2 -> ',' commands posforaux2\n");;
    break;}
case 81:
#line 193 "yacc_syntax.y"
{printf("posforaux2 -> LAMBDA\n");;
    break;}
case 82:
#line 196 "yacc_syntax.y"
{printf("whileloop -> 'enquanto' '(' expr ')' 'faca' callcommand\n");;
    break;}
case 83:
#line 199 "yacc_syntax.y"
{printf("repeatloop -> 'repita' commands 'ate' expr \n");;
    break;}
case 84:
#line 202 "yacc_syntax.y"
{printf("conditional -> ifcond\n");;
    break;}
case 85:
#line 203 "yacc_syntax.y"
{printf("conditional -> casecond\n");;
    break;}
case 86:
#line 206 "yacc_syntax.y"
{printf("ifcond -> 'se' '(' expr ')' 'entao' callcommand ifcondaux\n");;
    break;}
case 87:
#line 209 "yacc_syntax.y"
{printf("ifcondaux -> 'senao' callcommand \n");;
    break;}
case 88:
#line 210 "yacc_syntax.y"
{printf("ifcondaux -> LAMBDA \n");;
    break;}
case 89:
#line 214 "yacc_syntax.y"
{printf("casecond -> 'caso' '(' expr ')' 'seja' caselist casecondaux\n");;
    break;}
case 90:
#line 217 "yacc_syntax.y"
{printf("casecondaux -> 'fim'\n");;
    break;}
case 91:
#line 218 "yacc_syntax.y"
{printf("casecondaux -> 'senao' commands 'fim'\n");;
    break;}
case 92:
#line 221 "yacc_syntax.y"
{printf("caselist -> caseclause caselistaux\n");;
    break;}
case 93:
#line 224 "yacc_syntax.y"
{printf("caselistaux -> ';' caselistaux2\n");;
    break;}
case 94:
#line 225 "yacc_syntax.y"
{printf("caselistaux -> LAMBDA\n");;
    break;}
case 95:
#line 228 "yacc_syntax.y"
{printf("caselistaux2 -> caseclause caselistaux\n");;
    break;}
case 96:
#line 229 "yacc_syntax.y"
{printf("caselistaux2 -> LAMBDA\n");;
    break;}
case 97:
#line 232 "yacc_syntax.y"
{printf("caseclause -> atomiclist ':' callcommand\n");;
    break;}
case 98:
#line 235 "yacc_syntax.y"
{printf("expressionlist -> expr expressionlistaux\n");;
    break;}
case 99:
#line 238 "yacc_syntax.y"
{printf("expressionlistaux -> ',' expr expressionlistaux\n");;
    break;}
case 100:
#line 239 "yacc_syntax.y"
{printf("expressionlistaux -> LAMBDA\n");;
    break;}
case 101:
#line 242 "yacc_syntax.y"
{printf("expr -> andfact orfact\n");;
    break;}
case 102:
#line 245 "yacc_syntax.y"
{printf("orfact -> OR andfact orfact\n");;
    break;}
case 103:
#line 246 "yacc_syntax.y"
{printf("orfact -> LAMBDA\n");;
    break;}
case 104:
#line 249 "yacc_syntax.y"
{printf("andfact -> notfact andfactaux\n");;
    break;}
case 105:
#line 252 "yacc_syntax.y"
{printf("andfactaux -> AND notfact andfactaux\n");;
    break;}
case 106:
#line 253 "yacc_syntax.y"
{printf("andfactaux -> LAMBDA\n");;
    break;}
case 107:
#line 256 "yacc_syntax.y"
{printf("notfact -> '!' expreq\n");;
    break;}
case 108:
#line 257 "yacc_syntax.y"
{printf("notfact -> expreq\n");;
    break;}
case 109:
#line 260 "yacc_syntax.y"
{printf("expreq -> numericexpr expreqaux\n");;
    break;}
case 110:
#line 263 "yacc_syntax.y"
{printf("expreqaux -> EQUAL numericexpr expreqaux\n");;
    break;}
case 111:
#line 264 "yacc_syntax.y"
{printf("expreqaux -> NOTEQ numericexpr expreqaux\n");;
    break;}
case 112:
#line 265 "yacc_syntax.y"
{printf("expreqaux -> '>' numericexpr expreqaux\n");;
    break;}
case 113:
#line 266 "yacc_syntax.y"
{printf("expreqaux -> '<' numericexpr expreqaux\n");;
    break;}
case 114:
#line 267 "yacc_syntax.y"
{printf("expreqaux -> LESSEQ numericexpr expreqaux\n");;
    break;}
case 115:
#line 268 "yacc_syntax.y"
{printf("expreqaux -> GREATEQ numericexpr expreqaux\n");;
    break;}
case 116:
#line 269 "yacc_syntax.y"
{printf("expreqaux -> LAMBDA\n");;
    break;}
case 117:
#line 272 "yacc_syntax.y"
{printf("numericexpr -> exprmul exprsum\n");;
    break;}
case 118:
#line 275 "yacc_syntax.y"
{printf("exprsum -> '+' exprmul exprsum\n");;
    break;}
case 119:
#line 276 "yacc_syntax.y"
{printf("exprsum -> '-' exprmul exprsum\n");;
    break;}
case 120:
#line 277 "yacc_syntax.y"
{printf("exprsum -> LAMBDA\n");;
    break;}
case 121:
#line 280 "yacc_syntax.y"
{printf("exprmul -> simpleexpr exprmulaux\n");;
    break;}
case 122:
#line 283 "yacc_syntax.y"
{printf("exprmulaux -> '*' simpleexpr exprmulaux\n");;
    break;}
case 123:
#line 284 "yacc_syntax.y"
{printf("exprmulaux -> '/' simpleexpr exprmulaux\n");;
    break;}
case 124:
#line 285 "yacc_syntax.y"
{printf("exprmulaux -> LAMBDA\n");;
    break;}
case 125:
#line 288 "yacc_syntax.y"
{printf("simpleexpr -> atomic optrange\n");;
    break;}
case 126:
#line 289 "yacc_syntax.y"
{printf("simpleexpr -> optunary optbracket\n");;
    break;}
case 127:
#line 290 "yacc_syntax.y"
{printf("simpleexpr -> '(' expr ')'\n");;
    break;}
case 128:
#line 293 "yacc_syntax.y"
{printf("optrange -> DOUBLEDOT atomic\n");;
    break;}
case 129:
#line 294 "yacc_syntax.y"
{printf("optrange -> LAMBDA\n");;
    break;}
case 130:
#line 297 "yacc_syntax.y"
{printf("optunary -> '-'\n");;
    break;}
case 131:
#line 298 "yacc_syntax.y"
{printf("optunary -> '+'\n");;
    break;}
case 132:
#line 301 "yacc_syntax.y"
{printf("optbracket -> '(' expr ')'\n");;
    break;}
case 133:
#line 302 "yacc_syntax.y"
{printf("optbracket -> atomic\n");;
    break;}
case 134:
#line 305 "yacc_syntax.y"
{printf("idlist -> ID idlistaux\n");;
    break;}
case 135:
#line 308 "yacc_syntax.y"
{printf("idlistaux -> ',' ID idlistaux\n");;
    break;}
case 136:
#line 309 "yacc_syntax.y"
{printf("idlistaux -> LAMBDA\n");;
    break;}
case 137:
#line 312 "yacc_syntax.y"
{printf("type -> INT_TYPE\n");;
    break;}
case 138:
#line 313 "yacc_syntax.y"
{printf("type -> REAL_TYPE\n");;
    break;}
case 139:
#line 314 "yacc_syntax.y"
{printf("type -> HEXA_TYPE\n");;
    break;}
case 140:
#line 315 "yacc_syntax.y"
{printf("type -> STRING_TYPE\n");;
    break;}
case 141:
#line 316 "yacc_syntax.y"
{printf("type -> ID\n");;
    break;}
case 142:
#line 319 "yacc_syntax.y"
{printf("literal -> INT_VALUE\n");;
    break;}
case 143:
#line 320 "yacc_syntax.y"
{printf("literal -> REAL_VALUE\n");;
    break;}
case 144:
#line 321 "yacc_syntax.y"
{printf("literal -> HEXA_VALUE\n");;
    break;}
case 145:
#line 322 "yacc_syntax.y"
{printf("literal -> BOOL_VALUE\n");;
    break;}
case 146:
#line 323 "yacc_syntax.y"
{printf("literal -> STRING_VALUE\n");;
    break;}
case 147:
#line 326 "yacc_syntax.y"
{printf("atomic -> literal\n");;
    break;}
case 148:
#line 327 "yacc_syntax.y"
{printf("atomic -> id\n");;
    break;}
case 149:
#line 330 "yacc_syntax.y"
{printf("id -> ID idaux\n");;
    break;}
case 150:
#line 333 "yacc_syntax.y"
{printf("idaux -> '[' expressionlist ']'\n");;
    break;}
case 151:
#line 334 "yacc_syntax.y"
{printf("idaux -> '.' id\n");;
    break;}
case 152:
#line 335 "yacc_syntax.y"
{printf("idaux -> '(' expressionlist ')'\n");;
    break;}
case 153:
#line 336 "yacc_syntax.y"
{printf("idaux -> LAMBDA\n");;
    break;}
case 154:
#line 339 "yacc_syntax.y"
{printf("atomiclist -> atomic atomiclistaux\n");;
    break;}
case 155:
#line 342 "yacc_syntax.y"
{printf("atomiclistaux -> ',' atomic atomiclistaux\n");;
    break;}
case 156:
#line 343 "yacc_syntax.y"
{printf("atomiclistaux -> LAMBDA\n");;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 346 "yacc_syntax.y"
                     /* C code */

void success() {
	printf("\033[0;32mparse success\033[0m\n"); 
	exit(1);
}

int main() {
	return yyparse();
}

void yyerror (char *s) {
	fprintf(stderr,"%s:", s);
	//fprintf(stderr,"Line: %d | Column: %d\n ", yylval.token->line, yylval.token->column);
	fprintf(stderr,"%d:%d: No expected '%s'\n", yylval.token->line, yylval.token->column, yylval.token->value);
}
