#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from yacc_syntax.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "yacc_syntax.y"

#include "../../token.c"
#include <stdio.h>     /* C declarations used in actions */
#include <stdlib.h>

void yyerror (char *s); 

int yylex();

void success();

void p(char *s);
void placeTab();

void add_tab();
void rem_tab();
int scopo;


#line 21 "yacc_syntax.y"
typedef union {Token* token;} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	HEXA_VALUE	258
#define	INT_VALUE	259
#define	REAL_VALUE	260
#define	FINAL	261
#define	BOOL_VALUE	262
#define	CONTINUE	263
#define	ID	264
#define	INT	265
#define	REAL	266
#define	BOOL	267
#define	STRING	268
#define	VECTOR	269
#define	PROG	270
#define	INIT	271
#define	END	272
#define	OF	273
#define	VAR	274
#define	LABEL	275
#define	STRUCT	276
#define	TYPE	277
#define	CONST	278
#define	RETURN	279
#define	JUMP	280
#define	FOR	281
#define	WHILE	282
#define	DO	283
#define	REPEAT	284
#define	UNTIL	285
#define	IF	286
#define	THEN	287
#define	ELSE	288
#define	CASE	289
#define	BE	290
#define	FUNC	291
#define	PROC	292
#define	BREAK	293
#define	REF	294
#define	AND	295
#define	OR	296
#define	LESSEQ	297
#define	GREATEQ	298
#define	EQUAL	299
#define	NOTEQ	300
#define	DOUBLEDOT	301
#define	STRING_VALUE	302
#define	CASSIGN	303
#define	WRITE	304
#define	READ	305


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int HEXA_VALUE;
static const int INT_VALUE;
static const int REAL_VALUE;
static const int FINAL;
static const int BOOL_VALUE;
static const int CONTINUE;
static const int ID;
static const int INT;
static const int REAL;
static const int BOOL;
static const int STRING;
static const int VECTOR;
static const int PROG;
static const int INIT;
static const int END;
static const int OF;
static const int VAR;
static const int LABEL;
static const int STRUCT;
static const int TYPE;
static const int CONST;
static const int RETURN;
static const int JUMP;
static const int FOR;
static const int WHILE;
static const int DO;
static const int REPEAT;
static const int UNTIL;
static const int IF;
static const int THEN;
static const int ELSE;
static const int CASE;
static const int BE;
static const int FUNC;
static const int PROC;
static const int BREAK;
static const int REF;
static const int AND;
static const int OR;
static const int LESSEQ;
static const int GREATEQ;
static const int EQUAL;
static const int NOTEQ;
static const int DOUBLEDOT;
static const int STRING_VALUE;
static const int CASSIGN;
static const int WRITE;
static const int READ;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,HEXA_VALUE=258
	,INT_VALUE=259
	,REAL_VALUE=260
	,FINAL=261
	,BOOL_VALUE=262
	,CONTINUE=263
	,ID=264
	,INT=265
	,REAL=266
	,BOOL=267
	,STRING=268
	,VECTOR=269
	,PROG=270
	,INIT=271
	,END=272
	,OF=273
	,VAR=274
	,LABEL=275
	,STRUCT=276
	,TYPE=277
	,CONST=278
	,RETURN=279
	,JUMP=280
	,FOR=281
	,WHILE=282
	,DO=283
	,REPEAT=284
	,UNTIL=285
	,IF=286
	,THEN=287
	,ELSE=288
	,CASE=289
	,BE=290
	,FUNC=291
	,PROC=292
	,BREAK=293
	,REF=294
	,AND=295
	,OR=296
	,LESSEQ=297
	,GREATEQ=298
	,EQUAL=299
	,NOTEQ=300
	,DOUBLEDOT=301
	,STRING_VALUE=302
	,CASSIGN=303
	,WRITE=304
	,READ=305


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::HEXA_VALUE=258;
const int YY_parse_CLASS::INT_VALUE=259;
const int YY_parse_CLASS::REAL_VALUE=260;
const int YY_parse_CLASS::FINAL=261;
const int YY_parse_CLASS::BOOL_VALUE=262;
const int YY_parse_CLASS::CONTINUE=263;
const int YY_parse_CLASS::ID=264;
const int YY_parse_CLASS::INT=265;
const int YY_parse_CLASS::REAL=266;
const int YY_parse_CLASS::BOOL=267;
const int YY_parse_CLASS::STRING=268;
const int YY_parse_CLASS::VECTOR=269;
const int YY_parse_CLASS::PROG=270;
const int YY_parse_CLASS::INIT=271;
const int YY_parse_CLASS::END=272;
const int YY_parse_CLASS::OF=273;
const int YY_parse_CLASS::VAR=274;
const int YY_parse_CLASS::LABEL=275;
const int YY_parse_CLASS::STRUCT=276;
const int YY_parse_CLASS::TYPE=277;
const int YY_parse_CLASS::CONST=278;
const int YY_parse_CLASS::RETURN=279;
const int YY_parse_CLASS::JUMP=280;
const int YY_parse_CLASS::FOR=281;
const int YY_parse_CLASS::WHILE=282;
const int YY_parse_CLASS::DO=283;
const int YY_parse_CLASS::REPEAT=284;
const int YY_parse_CLASS::UNTIL=285;
const int YY_parse_CLASS::IF=286;
const int YY_parse_CLASS::THEN=287;
const int YY_parse_CLASS::ELSE=288;
const int YY_parse_CLASS::CASE=289;
const int YY_parse_CLASS::BE=290;
const int YY_parse_CLASS::FUNC=291;
const int YY_parse_CLASS::PROC=292;
const int YY_parse_CLASS::BREAK=293;
const int YY_parse_CLASS::REF=294;
const int YY_parse_CLASS::AND=295;
const int YY_parse_CLASS::OR=296;
const int YY_parse_CLASS::LESSEQ=297;
const int YY_parse_CLASS::GREATEQ=298;
const int YY_parse_CLASS::EQUAL=299;
const int YY_parse_CLASS::NOTEQ=300;
const int YY_parse_CLASS::DOUBLEDOT=301;
const int YY_parse_CLASS::STRING_VALUE=302;
const int YY_parse_CLASS::CASSIGN=303;
const int YY_parse_CLASS::WRITE=304;
const int YY_parse_CLASS::READ=305;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		471
#define	YYFLAG		-32768
#define	YYNTBASE	67

#define YYTRANSLATE(x) ((unsigned)(x) <= 305 ? yytranslate[x] : 308)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    59,     2,     2,     2,     2,     2,     2,    55,
    56,    64,    62,    57,    63,    66,    65,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    58,    51,    61,
    54,    60,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    52,     2,    53,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     2,     3,     4,    14,    15,    16,    22,    23,
    28,    29,    31,    33,    35,    37,    39,    40,    41,    42,
    43,    55,    56,    57,    58,    66,    67,    70,    71,    76,
    77,    78,    83,    84,    85,    86,    94,    97,    99,   100,
   104,   105,   106,   107,   108,   109,   118,   120,   122,   123,
   124,   125,   132,   135,   136,   137,   143,   144,   148,   149,
   152,   153,   158,   159,   160,   161,   166,   167,   168,   169,
   170,   181,   183,   185,   186,   187,   188,   189,   190,   191,
   205,   206,   207,   208,   209,   210,   211,   212,   213,   231,
   233,   234,   235,   236,   243,   244,   245,   246,   255,   256,
   260,   261,   263,   264,   265,   268,   269,   272,   273,   276,
   278,   280,   281,   284,   285,   288,   289,   293,   294,   297,
   299,   302,   303,   307,   308,   309,   313,   314,   318,   319,
   320,   324,   325,   326,   333,   334,   335,   342,   343,   347,
   348,   351,   352,   355,   356,   359,   360,   361,   362,   363,
   374,   375,   376,   384,   386,   387,   388,   389,   396,   397,
   398,   399,   408,   409,   411,   412,   415,   416,   421,   422,
   423,   424,   425,   426,   437,   438,   439,   440,   448,   449,
   452,   453,   456,   457,   458,   459,   460,   461,   474,   475,
   476,   481,   482,   483,   484,   485,   486,   498,   499,   500,
   504,   505,   506,   507,   508,   516,   519,   520,   524,   525,
   528,   529,   530,   531,   537,   540,   541,   546,   547,   550,
   551,   556,   557,   560,   561,   566,   567,   568,   572,   574,
   577,   578,   583,   584,   589,   590,   595,   596,   601,   602,
   607,   608,   613,   614,   617,   618,   623,   624,   629,   630,
   633,   634,   639,   640,   645,   646,   649,   652,   653,   654,
   660,   661,   665,   666,   667,   670,   671,   674,   675,   676,
   682,   684,   685,   689,   690,   691,   697,   698,   699,   702,
   703,   706,   707,   710,   711,   714,   715,   718,   719,   722,
   723,   726,   727,   730,   731,   734,   735,   738,   740,   742,
   743,   747,   748,   749,   755,   756,   760,   761,   765,   766,
   767,   771,   772,   775,   778,   779,   784
};

static const short yyrhs[] = {    -1,
     0,     0,     0,    15,    68,     9,    69,    51,    70,    75,
    71,    72,     0,     0,     0,    16,    73,   150,    74,    17,
     0,     0,    77,    51,    76,    75,     0,     0,    92,     0,
    99,     0,   116,     0,   119,     0,   124,     0,     0,     0,
     0,     0,    14,    79,    52,    80,    87,    53,    81,    18,
    82,   282,    83,     0,     0,     0,     0,    54,    84,    55,
    85,   239,    56,    86,     0,     0,    90,    88,     0,     0,
    57,    89,    90,    88,     0,     0,     0,   294,    46,    91,
   294,     0,     0,     0,     0,    93,    19,    94,   277,    58,
    95,    96,     0,   282,    97,     0,    78,     0,     0,    54,
    98,   242,     0,     0,     0,     0,     0,     0,   100,    22,
   101,     9,   102,    48,   103,   104,     0,    78,     0,   105,
     0,     0,     0,     0,    21,   106,   113,   107,    17,   108,
     0,   294,   111,     0,     0,     0,    55,   109,   277,    56,
   110,     0,     0,    46,   112,   294,     0,     0,    92,   114,
     0,     0,    51,   115,    92,   114,     0,     0,     0,     0,
   117,    20,   118,   277,     0,     0,     0,     0,     0,   120,
    23,   121,   277,    58,   122,   282,    54,   123,   242,     0,
   125,     0,   132,     0,     0,     0,     0,     0,     0,     0,
   126,    37,   127,     9,   128,    55,   129,   141,    56,   130,
    75,   131,    72,     0,     0,     0,     0,     0,     0,     0,
     0,     0,   133,    36,   134,     9,   135,    55,   136,   141,
    56,   137,    58,   138,   282,   139,    75,   140,    72,     0,
   142,     0,     0,     0,     0,     9,   143,    58,   144,   282,
   148,     0,     0,     0,     0,    39,   145,     9,   146,    58,
   147,   282,   148,     0,     0,    57,   149,   142,     0,     0,
   159,     0,     0,     0,   152,    38,     0,     0,   153,   167,
     0,     0,   154,   170,     0,   175,     0,    72,     0,     0,
   155,   173,     0,     0,   156,     8,     0,     0,   157,   295,
   162,     0,     0,   158,   165,     0,   208,     0,   151,   160,
     0,     0,    51,   161,   159,     0,     0,     0,    58,   163,
   151,     0,     0,    54,   164,   242,     0,     0,     0,    25,
   166,     9,     0,     0,     0,    49,   168,    55,   169,   239,
    56,     0,     0,     0,    50,   171,    55,   172,   239,    56,
     0,     0,    24,   174,   242,     0,     0,   176,   179,     0,
     0,   177,   199,     0,     0,   178,   204,     0,     0,     0,
     0,     0,    26,   180,    55,   181,   184,    56,   182,    28,
   183,   151,     0,     0,     0,   187,    51,   185,   242,    51,
   186,   195,     0,   188,     0,     0,     0,     0,     9,   189,
    54,   190,   242,   191,     0,     0,     0,     0,    57,   192,
     9,   193,    54,   194,   242,   191,     0,     0,   196,     0,
     0,   159,   197,     0,     0,    57,   198,   159,   197,     0,
     0,     0,     0,     0,     0,    27,   200,    55,   201,   242,
    56,   202,    28,   203,   151,     0,     0,     0,     0,    29,
   205,   159,   206,    30,   207,   242,     0,     0,   209,   211,
     0,     0,   210,   220,     0,     0,     0,     0,     0,     0,
    31,   212,    55,   213,   242,    56,   214,    32,   215,   151,
   216,   217,     0,     0,     0,   218,    33,   219,   151,     0,
     0,     0,     0,     0,     0,    34,   221,    55,   222,   242,
    56,   223,    35,   224,   232,   225,     0,     0,     0,   226,
    17,   227,     0,     0,     0,     0,     0,   228,    33,   229,
   159,   230,    17,   231,     0,   236,   233,     0,     0,    51,
   234,   235,     0,     0,   236,   233,     0,     0,     0,     0,
   237,   305,    58,   238,   151,     0,   242,   240,     0,     0,
    57,   241,   242,   240,     0,     0,   245,   243,     0,     0,
    41,   244,   245,   243,     0,     0,   248,   246,     0,     0,
    40,   247,   248,   246,     0,     0,     0,    59,   249,   250,
     0,   250,     0,   258,   251,     0,     0,    44,   252,   258,
   251,     0,     0,    45,   253,   258,   251,     0,     0,    60,
   254,   258,   251,     0,     0,    61,   255,   258,   251,     0,
     0,    42,   256,   258,   251,     0,     0,    43,   257,   258,
   251,     0,     0,   262,   259,     0,     0,    62,   260,   262,
   259,     0,     0,    63,   261,   262,   259,     0,     0,   266,
   263,     0,     0,    64,   264,   266,   263,     0,     0,    65,
   265,   266,   263,     0,     0,   294,   269,     0,   271,   274,
     0,     0,     0,    55,   267,   242,    56,   268,     0,     0,
    46,   270,   294,     0,     0,     0,    63,   272,     0,     0,
    62,   273,     0,     0,     0,    55,   275,   242,    56,   276,
     0,   294,     0,     0,     9,   278,   279,     0,     0,     0,
    57,   280,     9,   281,   279,     0,     0,     0,    10,   283,
     0,     0,    11,   284,     0,     0,    12,   285,     0,     0,
    13,   286,     0,     0,     9,   287,     0,     0,     4,   289,
     0,     0,     5,   290,     0,     0,     3,   291,     0,     0,
     7,   292,     0,     0,    47,   293,     0,   288,     0,   295,
     0,     0,     9,   296,   297,     0,     0,     0,    52,   298,
   239,    53,   299,     0,     0,    66,   300,   295,     0,     0,
    55,   301,   302,     0,     0,     0,   239,    56,   303,     0,
     0,    56,   304,     0,   294,   306,     0,     0,    57,   307,
   294,   306,     0,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    33,    33,    33,    33,    33,    36,    36,    36,    39,    39,
    40,    43,    44,    45,    46,    47,    50,    50,    50,    50,
    50,    53,    53,    53,    53,    54,    57,    60,    60,    61,
    64,    64,    67,    67,    67,    67,    70,    71,    74,    74,
    75,    78,    78,    78,    78,    78,    81,    82,    85,    85,
    85,    85,    86,    87,    87,    87,    90,    90,    91,    94,
    97,    97,    98,   101,   101,   101,   104,   104,   104,   104,
   104,   107,   108,   111,   111,   111,   111,   111,   111,   112,
   114,   114,   114,   114,   114,   114,   114,   114,   115,   117,
   118,   121,   121,   121,   122,   122,   122,   122,   125,   125,
   126,   130,   131,   134,   134,   135,   135,   136,   136,   137,
   138,   139,   139,   140,   140,   141,   141,   142,   142,   143,
   146,   149,   149,   150,   153,   153,   154,   154,   155,   158,
   158,   161,   161,   161,   164,   164,   164,   167,   167,   170,
   170,   171,   171,   172,   172,   175,   175,   175,   175,   176,
   178,   178,   178,   181,   182,   185,   185,   185,   188,   188,
   188,   188,   189,   192,   193,   196,   199,   199,   200,   203,
   203,   203,   203,   204,   206,   206,   206,   206,   209,   209,
   210,   210,   213,   213,   213,   213,   213,   213,   216,   216,
   217,   217,   221,   221,   221,   221,   221,   224,   224,   224,
   225,   225,   225,   225,   225,   228,   231,   231,   232,   235,
   236,   239,   239,   239,   242,   245,   245,   246,   249,   252,
   252,   253,   256,   259,   259,   260,   263,   263,   264,   267,
   270,   270,   271,   271,   272,   272,   273,   273,   274,   274,
   275,   275,   276,   279,   282,   282,   283,   283,   284,   287,
   290,   290,   291,   291,   292,   295,   296,   297,   297,   297,
   300,   300,   301,   304,   304,   305,   305,   308,   308,   308,
   309,   312,   312,   315,   315,   315,   316,   319,   319,   320,
   320,   321,   321,   322,   322,   323,   323,   326,   326,   327,
   327,   328,   328,   329,   329,   330,   330,   333,   334,   337,
   337,   340,   340,   340,   341,   341,   342,   342,   343,   346,
   346,   347,   347,   350,   353,   353,   354
};

static const char * const yytname[] = {   "$","error","$illegal.","HEXA_VALUE",
"INT_VALUE","REAL_VALUE","FINAL","BOOL_VALUE","CONTINUE","ID","INT","REAL","BOOL",
"STRING","VECTOR","PROG","INIT","END","OF","VAR","LABEL","STRUCT","TYPE","CONST",
"RETURN","JUMP","FOR","WHILE","DO","REPEAT","UNTIL","IF","THEN","ELSE","CASE",
"BE","FUNC","PROC","BREAK","REF","AND","OR","LESSEQ","GREATEQ","EQUAL","NOTEQ",
"DOUBLEDOT","STRING_VALUE","CASSIGN","WRITE","READ","';'","'['","']'","'='",
"'('","')'","','","':'","'!'","'>'","'<'","'+'","'-'","'*'","'/'","'.'","program",
"@1","@2","@3","@4","block","@5","@6","prevdec","@7","declaration","arraydec",
"@8","@9","@10","@11","arraydecaux","@12","@13","@14","rangelist","rangelistaux",
"@15","range","@16","vardec","@17","@18","@19","varconstruction","decwithassign",
"@20","usertype","@21","@22","@23","@24","typedec","typedecaux","@25","@26",
"@27","@28","@29","typedecauxrange","@30","vardeclist","vardeclistaux","@31",
"labeldec","@32","@33","constdec","@34","@35","@36","@37","abstractiondec","procdec",
"@38","@39","@40","@41","@42","@43","funcdec","@44","@45","@46","@47","@48",
"@49","@50","@51","parameters","paramsaux","@52","@53","@54","@55","@56","paramslist",
"@57","prevcommand","callcommand","@58","@59","@60","@61","@62","@63","@64",
"commands","commandsaux","@65","callidbegin","@66","@67","calllabel","@68","write",
"@69","@70","read","@71","@72","return","@73","loop","@74","@75","@76","forloop",
"@77","@78","@79","@80","forstruct","@81","@82","prevfor","varassignlist","@83",
"@84","varassignlistaux","@85","@86","@87","posfor","posforaux","posforaux2",
"@88","whileloop","@89","@90","@91","@92","repeatloop","@93","@94","@95","conditional",
"@96","@97","ifcond","@98","@99","@100","@101","@102","ifcondaux","@103","@104",
"casecond","@105","@106","@107","@108","casecondaux","@109","@110","@111","@112",
"@113","@114","caselist","caselistaux","@115","caselistaux2","caseclause","@116",
"@117","expressionlist","expressionlistaux","@118","expr","orfact","@119","andfact",
"andfactaux","@120","notfact","@121","expreq","expreqaux","@122","@123","@124",
"@125","@126","@127","numericexpr","exprsum","@128","@129","exprmul","exprmulaux",
"@130","@131","simpleexpr","@132","@133","optrange","@134","optunary","@135",
"@136","optbracket","@137","@138","idlist","@139","idlistaux","@140","@141",
"type","@142","@143","@144","@145","@146","literal","@147","@148","@149","@150",
"@151","atomic","id","@152","idaux","@153","@154","@155","@156","idauxexpraux",
"@157","@158","atomiclist","atomiclistaux","@159",""
};
#endif

static const short yyr1[] = {     0,
    68,    69,    70,    71,    67,    73,    74,    72,    76,    75,
    75,    77,    77,    77,    77,    77,    79,    80,    81,    82,
    78,    84,    85,    86,    83,    83,    87,    89,    88,    88,
    91,    90,    93,    94,    95,    92,    96,    96,    98,    97,
    97,   100,   101,   102,   103,    99,   104,   104,   106,   107,
   108,   105,   105,   109,   110,   105,   112,   111,   111,   113,
   115,   114,   114,   117,   118,   116,   120,   121,   122,   123,
   119,   124,   124,   126,   127,   128,   129,   130,   131,   125,
   133,   134,   135,   136,   137,   138,   139,   140,   132,   141,
   141,   143,   144,   142,   145,   146,   147,   142,   149,   148,
   148,   150,   150,   152,   151,   153,   151,   154,   151,   151,
   151,   155,   151,   156,   151,   157,   151,   158,   151,   151,
   159,   161,   160,   160,   163,   162,   164,   162,   162,   166,
   165,   168,   169,   167,   171,   172,   170,   174,   173,   176,
   175,   177,   175,   178,   175,   180,   181,   182,   183,   179,
   185,   186,   184,   187,   187,   189,   190,   188,   192,   193,
   194,   191,   191,   195,   195,   196,   198,   197,   197,   200,
   201,   202,   203,   199,   205,   206,   207,   204,   209,   208,
   210,   208,   212,   213,   214,   215,   216,   211,   218,   219,
   217,   217,   221,   222,   223,   224,   220,   226,   227,   225,
   228,   229,   230,   231,   225,   232,   234,   233,   233,   235,
   235,   237,   238,   236,   239,   241,   240,   240,   242,   244,
   243,   243,   245,   247,   246,   246,   249,   248,   248,   250,
   252,   251,   253,   251,   254,   251,   255,   251,   256,   251,
   257,   251,   251,   258,   260,   259,   261,   259,   259,   262,
   264,   263,   265,   263,   263,   266,   266,   267,   268,   266,
   270,   269,   269,   272,   271,   273,   271,   275,   276,   274,
   274,   278,   277,   280,   281,   279,   279,   283,   282,   284,
   282,   285,   282,   286,   282,   287,   282,   289,   288,   290,
   288,   291,   288,   292,   288,   293,   288,   294,   294,   296,
   295,   298,   299,   297,   300,   297,   301,   297,   297,   303,
   302,   304,   302,   305,   307,   306,   306
};

static const short yyr2[] = {     0,
     0,     0,     0,     0,     9,     0,     0,     5,     0,     4,
     0,     1,     1,     1,     1,     1,     0,     0,     0,     0,
    11,     0,     0,     0,     7,     0,     2,     0,     4,     0,
     0,     4,     0,     0,     0,     7,     2,     1,     0,     3,
     0,     0,     0,     0,     0,     8,     1,     1,     0,     0,
     0,     6,     2,     0,     0,     5,     0,     3,     0,     2,
     0,     4,     0,     0,     0,     4,     0,     0,     0,     0,
    10,     1,     1,     0,     0,     0,     0,     0,     0,    13,
     0,     0,     0,     0,     0,     0,     0,     0,    17,     1,
     0,     0,     0,     6,     0,     0,     0,     8,     0,     3,
     0,     1,     0,     0,     2,     0,     2,     0,     2,     1,
     1,     0,     2,     0,     2,     0,     3,     0,     2,     1,
     2,     0,     3,     0,     0,     3,     0,     3,     0,     0,
     3,     0,     0,     6,     0,     0,     6,     0,     3,     0,
     2,     0,     2,     0,     2,     0,     0,     0,     0,    10,
     0,     0,     7,     1,     0,     0,     0,     6,     0,     0,
     0,     8,     0,     1,     0,     2,     0,     4,     0,     0,
     0,     0,     0,    10,     0,     0,     0,     7,     0,     2,
     0,     2,     0,     0,     0,     0,     0,    12,     0,     0,
     4,     0,     0,     0,     0,     0,    11,     0,     0,     3,
     0,     0,     0,     0,     7,     2,     0,     3,     0,     2,
     0,     0,     0,     5,     2,     0,     4,     0,     2,     0,
     4,     0,     2,     0,     4,     0,     0,     3,     1,     2,
     0,     4,     0,     4,     0,     4,     0,     4,     0,     4,
     0,     4,     0,     2,     0,     4,     0,     4,     0,     2,
     0,     4,     0,     4,     0,     2,     2,     0,     0,     5,
     0,     3,     0,     0,     2,     0,     2,     0,     0,     5,
     1,     0,     3,     0,     0,     5,     0,     0,     2,     0,
     2,     0,     2,     0,     2,     0,     2,     0,     2,     0,
     2,     0,     2,     0,     2,     0,     2,     1,     1,     0,
     3,     0,     0,     5,     0,     3,     0,     3,     0,     0,
     3,     0,     2,     2,     0,     4,     0
};

static const short yydefact[] = {     0,
     1,     0,     2,     0,     3,    11,     4,     0,    12,     0,
    13,     0,    14,     0,    15,     0,    16,    72,     0,    73,
     0,     0,     9,    34,    43,    65,    68,    75,    82,     6,
     5,    11,     0,     0,     0,     0,     0,     0,   103,    10,
   272,     0,    44,    66,     0,    76,    83,   111,     7,   124,
     0,     0,     0,     0,     0,     0,     0,   102,   110,     0,
     0,     0,   120,     0,     0,   277,    35,     0,    69,     0,
     0,     0,   122,   121,   105,   132,   107,   135,   109,   138,
   113,   115,   300,   129,   130,   119,   146,   141,   170,   143,
   175,   145,   183,   180,   193,   182,   274,   273,     0,    45,
     0,    77,    84,     8,   104,     0,     0,     0,   309,   127,
   125,   117,     0,     0,     0,   104,     0,     0,     0,   286,
   278,   280,   282,   284,    17,    38,    36,    41,     0,     0,
    91,    91,   123,   133,   136,   292,   288,   290,   294,   296,
   258,   227,   266,   264,   139,   222,   226,   229,   243,   249,
   255,     0,   298,   263,   299,   302,   307,   305,   301,     0,
   104,   131,   147,   171,   176,   184,   194,   275,   287,   279,
   281,   283,   285,     0,    39,    37,    49,    54,    47,    46,
    48,    59,    70,    92,    95,     0,    90,     0,     0,     0,
   293,   289,   291,   295,   297,     0,     0,   267,   265,   220,
   219,   224,   223,   239,   241,   231,   233,   235,   237,   230,
   245,   247,   244,   251,   253,   250,   268,   257,   271,   261,
   256,     0,     0,     0,   128,   126,   155,     0,     0,     0,
     0,   277,    18,     0,    33,     0,    57,    53,     0,     0,
     0,    78,    85,     0,   218,     0,     0,   228,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,   312,     0,   308,   306,   156,     0,     0,
   154,     0,   177,     0,     0,   276,     0,    40,    63,    50,
     0,     0,    71,    93,    96,    11,     0,   134,   216,   215,
   137,   259,   222,   226,   243,   243,   243,   243,   243,   243,
   249,   249,   255,   255,     0,   262,   303,   313,   310,     0,
   148,   151,   172,     0,   185,   195,     0,    30,     0,    61,
    60,     0,    55,    58,     0,     0,    79,    86,     0,   260,
   221,   225,   240,   242,   232,   234,   236,   238,   246,   248,
   252,   254,   269,   304,   311,   157,     0,     0,     0,   178,
     0,     0,    19,    28,    27,    31,    33,    51,    56,   101,
    97,     0,     0,   218,   270,     0,   149,     0,   173,   186,
   196,     0,     0,     0,    63,    52,    99,    94,     0,    80,
    87,   217,   163,   104,   152,   104,   104,   212,    20,    30,
    32,    62,     0,   101,    11,   159,   158,   150,   104,   174,
   187,   198,   209,     0,     0,    29,   100,    98,    88,     0,
   169,   153,   164,   192,   197,     0,     0,   207,   206,   317,
     0,    26,     0,   160,   167,   166,   188,     0,   199,   202,
   212,   315,   314,   213,    22,    21,    89,     0,   104,   190,
   200,   104,   208,   209,     0,   104,     0,   161,   169,   104,
   203,   210,   317,   214,    23,     0,   168,   191,     0,   316,
     0,   163,   204,     0,   162,   205,    24,    25,     0,     0,
     0
};

static const short yydefgoto[] = {   469,
     2,     4,     6,    22,    48,    39,    72,     7,    32,     8,
   126,   174,   277,   372,   405,   436,   447,   461,   468,   317,
   355,   373,   318,   374,     9,    10,    33,    99,   127,   176,
   234,    11,    12,    34,    68,   129,   180,   181,   235,   322,
   376,   236,   359,   238,   282,   280,   321,   357,    13,    14,
    35,    15,    16,    36,   101,   239,    17,    18,    19,    37,
    70,   131,   286,   362,    20,    21,    38,    71,   132,   287,
   363,   395,   423,   186,   187,   240,   325,   241,   326,   379,
   378,   393,    49,    50,    51,    52,    53,    54,    55,    56,
    57,    58,    74,   105,   112,   161,   160,    86,   113,    77,
   106,   189,    79,   107,   190,    81,   108,    59,    60,    61,
    62,    88,   114,   227,   347,   384,   269,   348,   399,   270,
   271,   310,   366,   397,   410,   438,   456,   412,   413,   426,
   439,    90,   115,   228,   349,   386,    92,   116,   229,   314,
    63,    64,    65,    94,   117,   230,   351,   387,   414,   427,
   428,   450,    96,   118,   231,   352,   388,   415,   416,   441,
   417,   442,   459,   466,   402,   419,   431,   443,   403,   404,
   446,   244,   290,   329,   245,   201,   249,   146,   203,   250,
   147,   197,   148,   210,   253,   254,   255,   256,   251,   252,
   149,   213,   257,   258,   150,   216,   259,   260,   151,   196,
   330,   221,   262,   152,   199,   198,   218,   261,   365,    42,
    66,    98,   119,   232,   128,   170,   171,   172,   173,   169,
   153,   192,   193,   191,   194,   195,   154,   155,   109,   159,
   222,   344,   224,   223,   266,   345,   308,   421,   433,   445
};

static const short yypact[] = {    -4,
-32768,    12,-32768,   -19,-32768,    74,-32768,    -6,-32768,    31,
-32768,    39,-32768,    47,-32768,    54,-32768,-32768,    33,-32768,
    42,    66,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    74,    76,    79,    76,    76,    80,    86,   161,-32768,
-32768,    40,-32768,-32768,    46,-32768,-32768,-32768,-32768,    55,
    70,    60,    63,    93,   113,   114,   101,-32768,-32768,   103,
   100,   106,-32768,    99,   104,    89,-32768,   117,-32768,    82,
   112,   151,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   -35,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   150,-32768,
   131,-32768,-32768,-32768,   188,   116,   119,    24,     0,-32768,
-32768,-32768,   166,   121,   125,   188,   126,   127,   174,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   130,    98,   135,
     4,     4,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,   152,   154,-32768,    20,   -38,
   -30,   111,-32768,   145,-32768,-32768,-32768,-32768,-32768,    24,
   188,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   146,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   155,-32768,-32768,-32768,   144,-32768,   147,    24,    24,
-32768,-32768,-32768,-32768,-32768,    24,    37,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    24,    13,   114,-32768,-32768,   193,    24,   175,    24,
    24,    89,-32768,    24,-32768,    76,-32768,-32768,    24,   148,
   198,-32768,-32768,   160,   163,   162,   165,-32768,    24,    24,
    37,    37,    37,    37,    37,    37,    37,    37,    37,    37,
    24,    44,   171,-32768,   169,-32768,-32768,-32768,   170,   176,
-32768,   172,-32768,   178,   179,-32768,    44,-32768,   180,-32768,
   183,    44,-32768,-32768,-32768,    74,   182,-32768,-32768,-32768,
-32768,-32768,   152,   154,    20,    20,    20,    20,    20,    20,
   -38,   -38,   -30,   -30,   185,-32768,-32768,-32768,-32768,   189,
-32768,-32768,-32768,    24,-32768,-32768,   191,   199,   190,-32768,
-32768,   228,-32768,-32768,   131,   200,-32768,-32768,    24,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   218,    24,   229,-32768,
   227,   233,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   212,
-32768,    66,   131,   163,-32768,    24,-32768,   219,-32768,-32768,
-32768,   253,    44,    44,   180,-32768,-32768,-32768,   131,-32768,
-32768,-32768,   215,   188,-32768,   188,   188,-32768,-32768,   199,
-32768,-32768,     4,   212,    74,-32768,-32768,-32768,   123,-32768,
-32768,   240,   223,    44,   131,-32768,-32768,-32768,-32768,   266,
   222,-32768,-32768,   243,-32768,   263,   248,-32768,-32768,   225,
   226,   231,    66,-32768,-32768,-32768,-32768,   254,-32768,-32768,
    -3,-32768,-32768,-32768,-32768,-32768,-32768,   232,   188,-32768,
-32768,   188,-32768,   223,    44,   188,   234,-32768,   222,   188,
-32768,-32768,   225,-32768,-32768,    24,-32768,-32768,   271,-32768,
    24,   215,-32768,   235,-32768,-32768,-32768,-32768,   290,   293,
-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,-32768,   -22,-32768,-32768,   -31,-32768,-32768,
   168,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   -95,-32768,   -79,-32768,  -223,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   -76,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   173,   -93,-32768,-32768,-32768,-32768,-32768,
   -92,-32768,-32768,  -154,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,  -101,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,  -161,-32768,-32768,-32768,-32768,-32768,  -146,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,  -140,-32768,-32768,  -125,-32768,
-32768,  -184,   -57,-32768,  -106,    15,-32768,    61,    17,-32768,
    62,-32768,   118,   -34,-32768,-32768,-32768,-32768,-32768,-32768,
    -2,  -265,-32768,-32768,  -201,  -245,-32768,-32768,  -186,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   -27,
-32768,    81,-32768,-32768,   -96,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,  -126,   -46,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,  -139,-32768
};


#define	YYLAST		401


static const short yytable[] = {    31,
    40,   145,   182,   133,   130,   246,   226,    44,    45,    84,
     1,   279,   184,  -211,   165,   136,   137,   138,   110,   139,
     3,    83,   111,   211,   212,   219,   136,   137,   138,  -211,
   139,     5,    83,   214,   215,   339,   340,   263,   265,   136,
   137,   138,   185,   139,    23,    83,   136,   137,   138,    24,
   139,   156,    83,   225,   157,   301,   302,   341,   342,   140,
    25,   204,   205,   206,   207,   158,    26,   141,   264,    28,
   140,   142,   303,   304,   143,   144,    27,    29,   141,   208,
   209,    30,   142,   140,    41,   143,   144,    43,    46,   247,
   140,   141,   -33,   -64,    47,   -42,   -67,    67,   143,   144,
   136,   137,   138,    69,   139,    73,    83,    75,    76,   -81,
   -74,   125,    78,   136,   137,   138,    80,   139,   177,    83,
    82,   272,    83,   274,   275,    85,    89,   278,    87,    93,
  -114,  -116,   283,   375,    91,   306,   102,    95,    30,   120,
   121,   122,   123,   124,   140,    97,  -112,  -118,  -140,  -142,
   319,  -144,   178,  -179,   305,   324,  -181,   140,   120,   121,
   122,   123,   124,   125,   100,   217,   103,   104,  -114,  -116,
   134,  -106,  -108,   135,   162,   163,    30,   267,  -165,   164,
   166,   167,   168,   175,  -112,  -118,  -140,  -142,   183,  -144,
   220,  -179,   200,   202,  -181,  -114,  -116,   233,  -104,   242,
   237,   268,   243,    30,   273,   284,   285,   350,   281,  -106,
  -108,  -112,  -118,  -140,  -142,   288,  -144,   291,  -179,   289,
   292,  -181,   364,   307,   309,   311,   312,   313,   360,   398,
   320,   400,   401,   315,   316,   356,  -106,  -108,   323,   328,
   343,   368,   346,   353,   358,   367,   319,   391,   295,   296,
   297,   298,   299,   300,   327,   354,   369,   361,   370,   383,
   333,   334,   335,   336,   337,   338,   381,   371,   377,   385,
   389,   396,  -201,   418,   424,  -189,   464,   420,   425,   429,
   430,   432,   394,   434,   435,   448,   440,   463,   455,   470,
   467,   454,   471,   390,   406,   458,   179,   411,   392,   407,
   465,   408,   457,   452,   188,   444,   382,   331,   422,   293,
   332,   294,   276,   460,   248,     0,     0,     0,   453,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,   449,     0,   380,
   451,     0,     0,     0,     0,     0,     0,     0,     0,   462,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,   409,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
   437
};

static const short yycheck[] = {    22,
    32,   108,   129,   105,   101,   190,   161,    35,    36,    56,
    15,   235,     9,    17,   116,     3,     4,     5,    54,     7,
     9,     9,    58,    62,    63,   152,     3,     4,     5,    33,
     7,    51,     9,    64,    65,   301,   302,   222,   223,     3,
     4,     5,    39,     7,    51,     9,     3,     4,     5,    19,
     7,    52,     9,   160,    55,   257,   258,   303,   304,    47,
    22,    42,    43,    44,    45,    66,    20,    55,    56,    37,
    47,    59,   259,   260,    62,    63,    23,    36,    55,    60,
    61,    16,    59,    47,     9,    62,    63,     9,     9,   196,
    47,    55,    19,    20,     9,    22,    23,    58,    62,    63,
     3,     4,     5,    58,     7,    51,     9,    38,    49,    36,
    37,    14,    50,     3,     4,     5,    24,     7,    21,     9,
     8,   228,     9,   230,   231,    25,    27,   234,    26,    31,
     8,     9,   239,   357,    29,   262,    55,    34,    16,     9,
    10,    11,    12,    13,    47,    57,    24,    25,    26,    27,
   277,    29,    55,    31,   261,   282,    34,    47,     9,    10,
    11,    12,    13,    14,    48,    55,    55,    17,     8,     9,
    55,    49,    50,    55,     9,    55,    16,   224,    56,    55,
    55,    55,     9,    54,    24,    25,    26,    27,    54,    29,
    46,    31,    41,    40,    34,     8,     9,    52,    38,    56,
    46,     9,    56,    16,    30,    58,     9,   314,   236,    49,
    50,    24,    25,    26,    27,    56,    29,    56,    31,    57,
    56,    34,   329,    53,    56,    56,    51,    56,   325,   384,
    51,   386,   387,    56,    56,    46,    49,    50,    56,    58,
    56,   348,    54,    53,    17,    28,   373,   374,   251,   252,
   253,   254,   255,   256,   286,    57,    28,    58,    32,   366,
   295,   296,   297,   298,   299,   300,   363,    35,    57,    51,
    18,    57,    33,    51,     9,    33,   461,   404,    57,    17,
    33,    57,   379,    58,    54,    54,    33,    17,    55,     0,
    56,   446,     0,   373,   390,   450,   129,   399,   375,   393,
   462,   394,   449,   444,   132,   431,   364,   293,   405,   249,
   294,   250,   232,   453,   197,    -1,    -1,    -1,   445,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,   439,    -1,   362,
   442,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,   456,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,   395,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
   423
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 33 "yacc_syntax.y"
{p(" "); ;
    break;}
case 2:
#line 33 "yacc_syntax.y"
{p("");;
    break;}
case 3:
#line 33 "yacc_syntax.y"
{p(";\n");;
    break;}
case 4:
#line 33 "yacc_syntax.y"
{;
    break;}
case 5:
#line 33 "yacc_syntax.y"
{success();;
    break;}
case 6:
#line 36 "yacc_syntax.y"
{p("\n"); add_tab();;
    break;}
case 7:
#line 36 "yacc_syntax.y"
{printf("\n");rem_tab();placeTab();;
    break;}
case 8:
#line 36 "yacc_syntax.y"
{p("");;
    break;}
case 9:
#line 39 "yacc_syntax.y"
{p(";\n"); ;
    break;}
case 10:
#line 39 "yacc_syntax.y"
{;
    break;}
case 11:
#line 40 "yacc_syntax.y"
{;
    break;}
case 12:
#line 43 "yacc_syntax.y"
{;
    break;}
case 13:
#line 44 "yacc_syntax.y"
{;
    break;}
case 14:
#line 45 "yacc_syntax.y"
{;
    break;}
case 15:
#line 46 "yacc_syntax.y"
{;
    break;}
case 16:
#line 47 "yacc_syntax.y"
{;
    break;}
case 17:
#line 50 "yacc_syntax.y"
{p(" ");;
    break;}
case 18:
#line 50 "yacc_syntax.y"
{p("[ ");;
    break;}
case 19:
#line 50 "yacc_syntax.y"
{p("] ");;
    break;}
case 20:
#line 50 "yacc_syntax.y"
{p(" ");;
    break;}
case 21:
#line 50 "yacc_syntax.y"
{;
    break;}
case 22:
#line 53 "yacc_syntax.y"
{p("= ");;
    break;}
case 23:
#line 53 "yacc_syntax.y"
{p("( ");;
    break;}
case 24:
#line 53 "yacc_syntax.y"
{p(") ");;
    break;}
case 25:
#line 53 "yacc_syntax.y"
{;
    break;}
case 26:
#line 54 "yacc_syntax.y"
{;
    break;}
case 27:
#line 57 "yacc_syntax.y"
{;
    break;}
case 28:
#line 60 "yacc_syntax.y"
{p(", ");;
    break;}
case 29:
#line 60 "yacc_syntax.y"
{;
    break;}
case 30:
#line 61 "yacc_syntax.y"
{;
    break;}
case 31:
#line 64 "yacc_syntax.y"
{p(" ");;
    break;}
case 32:
#line 64 "yacc_syntax.y"
{;
    break;}
case 33:
#line 67 "yacc_syntax.y"
{placeTab();;
    break;}
case 34:
#line 67 "yacc_syntax.y"
{p(" ");;
    break;}
case 35:
#line 67 "yacc_syntax.y"
{p(": ");;
    break;}
case 36:
#line 67 "yacc_syntax.y"
{;
    break;}
case 37:
#line 70 "yacc_syntax.y"
{;
    break;}
case 38:
#line 71 "yacc_syntax.y"
{;
    break;}
case 39:
#line 74 "yacc_syntax.y"
{p("= ");;
    break;}
case 40:
#line 74 "yacc_syntax.y"
{;
    break;}
case 41:
#line 75 "yacc_syntax.y"
{;
    break;}
case 42:
#line 78 "yacc_syntax.y"
{placeTab();;
    break;}
case 43:
#line 78 "yacc_syntax.y"
{p(" ");;
    break;}
case 44:
#line 78 "yacc_syntax.y"
{p(" ");;
    break;}
case 45:
#line 78 "yacc_syntax.y"
{p(" ");;
    break;}
case 46:
#line 78 "yacc_syntax.y"
{;
    break;}
case 47:
#line 81 "yacc_syntax.y"
{;
    break;}
case 48:
#line 82 "yacc_syntax.y"
{;
    break;}
case 49:
#line 85 "yacc_syntax.y"
{p("\n"); add_tab();;
    break;}
case 50:
#line 85 "yacc_syntax.y"
{printf("\n"); rem_tab(); ;
    break;}
case 51:
#line 85 "yacc_syntax.y"
{p("");;
    break;}
case 52:
#line 85 "yacc_syntax.y"
{;
    break;}
case 53:
#line 86 "yacc_syntax.y"
{;
    break;}
case 54:
#line 87 "yacc_syntax.y"
{p("( ");;
    break;}
case 55:
#line 87 "yacc_syntax.y"
{p(") ");;
    break;}
case 56:
#line 87 "yacc_syntax.y"
{;
    break;}
case 57:
#line 90 "yacc_syntax.y"
{p(" ");;
    break;}
case 58:
#line 90 "yacc_syntax.y"
{;
    break;}
case 59:
#line 91 "yacc_syntax.y"
{;
    break;}
case 60:
#line 94 "yacc_syntax.y"
{;
    break;}
case 61:
#line 97 "yacc_syntax.y"
{p(";\n");;
    break;}
case 62:
#line 97 "yacc_syntax.y"
{;
    break;}
case 63:
#line 98 "yacc_syntax.y"
{;
    break;}
case 64:
#line 101 "yacc_syntax.y"
{placeTab();;
    break;}
case 65:
#line 101 "yacc_syntax.y"
{p(" ");;
    break;}
case 66:
#line 101 "yacc_syntax.y"
{;
    break;}
case 67:
#line 104 "yacc_syntax.y"
{placeTab();;
    break;}
case 68:
#line 104 "yacc_syntax.y"
{p(" ");;
    break;}
case 69:
#line 104 "yacc_syntax.y"
{p(": ");;
    break;}
case 70:
#line 104 "yacc_syntax.y"
{p("= ");;
    break;}
case 71:
#line 104 "yacc_syntax.y"
{;
    break;}
case 72:
#line 107 "yacc_syntax.y"
{;
    break;}
case 73:
#line 108 "yacc_syntax.y"
{;
    break;}
case 74:
#line 111 "yacc_syntax.y"
{placeTab();;
    break;}
case 75:
#line 111 "yacc_syntax.y"
{p(" ");;
    break;}
case 76:
#line 111 "yacc_syntax.y"
{p("");;
    break;}
case 77:
#line 111 "yacc_syntax.y"
{p("( ");;
    break;}
case 78:
#line 111 "yacc_syntax.y"
{p(")\n");add_tab();;
    break;}
case 79:
#line 111 "yacc_syntax.y"
{rem_tab();;
    break;}
case 81:
#line 114 "yacc_syntax.y"
{placeTab();;
    break;}
case 82:
#line 114 "yacc_syntax.y"
{p(" ");;
    break;}
case 83:
#line 114 "yacc_syntax.y"
{p("");;
    break;}
case 84:
#line 114 "yacc_syntax.y"
{p("( ");;
    break;}
case 85:
#line 114 "yacc_syntax.y"
{p(") ");;
    break;}
case 86:
#line 114 "yacc_syntax.y"
{p(": ");;
    break;}
case 87:
#line 114 "yacc_syntax.y"
{p("\n");add_tab();;
    break;}
case 88:
#line 114 "yacc_syntax.y"
{rem_tab();;
    break;}
case 90:
#line 117 "yacc_syntax.y"
{;
    break;}
case 91:
#line 118 "yacc_syntax.y"
{;
    break;}
case 92:
#line 121 "yacc_syntax.y"
{p("");;
    break;}
case 93:
#line 121 "yacc_syntax.y"
{p(": ");;
    break;}
case 94:
#line 121 "yacc_syntax.y"
{;
    break;}
case 95:
#line 122 "yacc_syntax.y"
{p(" ");;
    break;}
case 96:
#line 122 "yacc_syntax.y"
{p("");;
    break;}
case 97:
#line 122 "yacc_syntax.y"
{p(": ");;
    break;}
case 98:
#line 122 "yacc_syntax.y"
{;
    break;}
case 99:
#line 125 "yacc_syntax.y"
{p(", ");;
    break;}
case 100:
#line 125 "yacc_syntax.y"
{;
    break;}
case 101:
#line 126 "yacc_syntax.y"
{;
    break;}
case 102:
#line 130 "yacc_syntax.y"
{;
    break;}
case 103:
#line 131 "yacc_syntax.y"
{;
    break;}
case 104:
#line 134 "yacc_syntax.y"
{placeTab();;
    break;}
case 105:
#line 134 "yacc_syntax.y"
{p("");;
    break;}
case 106:
#line 135 "yacc_syntax.y"
{placeTab();;
    break;}
case 107:
#line 135 "yacc_syntax.y"
{;
    break;}
case 108:
#line 136 "yacc_syntax.y"
{placeTab();;
    break;}
case 109:
#line 136 "yacc_syntax.y"
{;
    break;}
case 110:
#line 137 "yacc_syntax.y"
{;
    break;}
case 111:
#line 138 "yacc_syntax.y"
{;
    break;}
case 112:
#line 139 "yacc_syntax.y"
{placeTab();;
    break;}
case 113:
#line 139 "yacc_syntax.y"
{;
    break;}
case 114:
#line 140 "yacc_syntax.y"
{placeTab();;
    break;}
case 115:
#line 140 "yacc_syntax.y"
{p("");;
    break;}
case 116:
#line 141 "yacc_syntax.y"
{placeTab();;
    break;}
case 117:
#line 141 "yacc_syntax.y"
{;
    break;}
case 118:
#line 142 "yacc_syntax.y"
{placeTab();;
    break;}
case 119:
#line 142 "yacc_syntax.y"
{;
    break;}
case 120:
#line 143 "yacc_syntax.y"
{;
    break;}
case 121:
#line 146 "yacc_syntax.y"
{;
    break;}
case 122:
#line 149 "yacc_syntax.y"
{p(";\n");;
    break;}
case 123:
#line 149 "yacc_syntax.y"
{;
    break;}
case 124:
#line 150 "yacc_syntax.y"
{;
    break;}
case 125:
#line 153 "yacc_syntax.y"
{p(":\n");;
    break;}
case 126:
#line 153 "yacc_syntax.y"
{;
    break;}
case 127:
#line 154 "yacc_syntax.y"
{p("= ");;
    break;}
case 128:
#line 154 "yacc_syntax.y"
{;
    break;}
case 129:
#line 155 "yacc_syntax.y"
{;
    break;}
case 130:
#line 158 "yacc_syntax.y"
{p(" ");;
    break;}
case 131:
#line 158 "yacc_syntax.y"
{p("");;
    break;}
case 132:
#line 161 "yacc_syntax.y"
{p("");;
    break;}
case 133:
#line 161 "yacc_syntax.y"
{p("( ");;
    break;}
case 134:
#line 161 "yacc_syntax.y"
{p(")");;
    break;}
case 135:
#line 164 "yacc_syntax.y"
{p("");;
    break;}
case 136:
#line 164 "yacc_syntax.y"
{p("( ");;
    break;}
case 137:
#line 164 "yacc_syntax.y"
{p(")");;
    break;}
case 138:
#line 167 "yacc_syntax.y"
{p(" ");;
    break;}
case 139:
#line 167 "yacc_syntax.y"
{;
    break;}
case 140:
#line 170 "yacc_syntax.y"
{placeTab();;
    break;}
case 141:
#line 170 "yacc_syntax.y"
{;
    break;}
case 142:
#line 171 "yacc_syntax.y"
{placeTab();;
    break;}
case 143:
#line 171 "yacc_syntax.y"
{;
    break;}
case 144:
#line 172 "yacc_syntax.y"
{placeTab();;
    break;}
case 145:
#line 172 "yacc_syntax.y"
{;
    break;}
case 146:
#line 175 "yacc_syntax.y"
{p("");;
    break;}
case 147:
#line 175 "yacc_syntax.y"
{p("( ");;
    break;}
case 148:
#line 175 "yacc_syntax.y"
{p(") ");;
    break;}
case 149:
#line 175 "yacc_syntax.y"
{p(" ");;
    break;}
case 151:
#line 178 "yacc_syntax.y"
{p(" ");;
    break;}
case 152:
#line 178 "yacc_syntax.y"
{p("; ");;
    break;}
case 153:
#line 178 "yacc_syntax.y"
{;
    break;}
case 154:
#line 181 "yacc_syntax.y"
{;
    break;}
case 155:
#line 182 "yacc_syntax.y"
{;
    break;}
case 156:
#line 185 "yacc_syntax.y"
{p(" ");;
    break;}
case 157:
#line 185 "yacc_syntax.y"
{p("= ");;
    break;}
case 158:
#line 185 "yacc_syntax.y"
{;
    break;}
case 159:
#line 188 "yacc_syntax.y"
{p(", ");;
    break;}
case 160:
#line 188 "yacc_syntax.y"
{p(" ");;
    break;}
case 161:
#line 188 "yacc_syntax.y"
{p("= ");;
    break;}
case 162:
#line 188 "yacc_syntax.y"
{;
    break;}
case 163:
#line 189 "yacc_syntax.y"
{;
    break;}
case 164:
#line 192 "yacc_syntax.y"
{;
    break;}
case 165:
#line 193 "yacc_syntax.y"
{;
    break;}
case 166:
#line 196 "yacc_syntax.y"
{;
    break;}
case 167:
#line 199 "yacc_syntax.y"
{p(", ");;
    break;}
case 168:
#line 199 "yacc_syntax.y"
{;
    break;}
case 169:
#line 200 "yacc_syntax.y"
{;
    break;}
case 170:
#line 203 "yacc_syntax.y"
{p("");;
    break;}
case 171:
#line 203 "yacc_syntax.y"
{p("( ");;
    break;}
case 172:
#line 203 "yacc_syntax.y"
{p(") ");;
    break;}
case 173:
#line 203 "yacc_syntax.y"
{p(" ");;
    break;}
case 175:
#line 206 "yacc_syntax.y"
{p("\n");add_tab();;
    break;}
case 176:
#line 206 "yacc_syntax.y"
{rem_tab();printf("\n");placeTab();;
    break;}
case 177:
#line 206 "yacc_syntax.y"
{p(" ");;
    break;}
case 178:
#line 206 "yacc_syntax.y"
{;
    break;}
case 179:
#line 209 "yacc_syntax.y"
{placeTab();;
    break;}
case 180:
#line 209 "yacc_syntax.y"
{;
    break;}
case 181:
#line 210 "yacc_syntax.y"
{placeTab();;
    break;}
case 182:
#line 210 "yacc_syntax.y"
{;
    break;}
case 183:
#line 213 "yacc_syntax.y"
{p(" ");;
    break;}
case 184:
#line 213 "yacc_syntax.y"
{p("( ");;
    break;}
case 185:
#line 213 "yacc_syntax.y"
{p(") ");;
    break;}
case 186:
#line 213 "yacc_syntax.y"
{p(" ");;
    break;}
case 187:
#line 213 "yacc_syntax.y"
{;
    break;}
case 188:
#line 213 "yacc_syntax.y"
{;
    break;}
case 189:
#line 216 "yacc_syntax.y"
{printf("\n");placeTab();;
    break;}
case 190:
#line 216 "yacc_syntax.y"
{p(" ");;
    break;}
case 192:
#line 217 "yacc_syntax.y"
{;
    break;}
case 193:
#line 221 "yacc_syntax.y"
{p("");;
    break;}
case 194:
#line 221 "yacc_syntax.y"
{p("( ");;
    break;}
case 195:
#line 221 "yacc_syntax.y"
{p(") ");;
    break;}
case 196:
#line 221 "yacc_syntax.y"
{p("\n");add_tab();;
    break;}
case 198:
#line 224 "yacc_syntax.y"
{printf("\n"); rem_tab(); placeTab();;
    break;}
case 199:
#line 224 "yacc_syntax.y"
{p("");;
    break;}
case 200:
#line 224 "yacc_syntax.y"
{;
    break;}
case 201:
#line 225 "yacc_syntax.y"
{placeTab();;
    break;}
case 202:
#line 225 "yacc_syntax.y"
{p("\n");;
    break;}
case 203:
#line 225 "yacc_syntax.y"
{printf("\n");;
    break;}
case 204:
#line 225 "yacc_syntax.y"
{p("");;
    break;}
case 205:
#line 225 "yacc_syntax.y"
{;
    break;}
case 206:
#line 228 "yacc_syntax.y"
{;
    break;}
case 207:
#line 231 "yacc_syntax.y"
{p(";\n");;
    break;}
case 208:
#line 231 "yacc_syntax.y"
{;
    break;}
case 209:
#line 232 "yacc_syntax.y"
{;
    break;}
case 210:
#line 235 "yacc_syntax.y"
{;
    break;}
case 211:
#line 236 "yacc_syntax.y"
{;
    break;}
case 212:
#line 239 "yacc_syntax.y"
{placeTab();;
    break;}
case 213:
#line 239 "yacc_syntax.y"
{p(":\n");add_tab();;
    break;}
case 214:
#line 239 "yacc_syntax.y"
{rem_tab();;
    break;}
case 215:
#line 242 "yacc_syntax.y"
{;
    break;}
case 216:
#line 245 "yacc_syntax.y"
{p(", ");;
    break;}
case 217:
#line 245 "yacc_syntax.y"
{;
    break;}
case 218:
#line 246 "yacc_syntax.y"
{;
    break;}
case 219:
#line 249 "yacc_syntax.y"
{;
    break;}
case 220:
#line 252 "yacc_syntax.y"
{p(" ");;
    break;}
case 221:
#line 252 "yacc_syntax.y"
{;
    break;}
case 222:
#line 253 "yacc_syntax.y"
{;
    break;}
case 223:
#line 256 "yacc_syntax.y"
{;
    break;}
case 224:
#line 259 "yacc_syntax.y"
{p(" ");;
    break;}
case 225:
#line 259 "yacc_syntax.y"
{;
    break;}
case 226:
#line 260 "yacc_syntax.y"
{;
    break;}
case 227:
#line 263 "yacc_syntax.y"
{p("!");;
    break;}
case 228:
#line 263 "yacc_syntax.y"
{;
    break;}
case 229:
#line 264 "yacc_syntax.y"
{;
    break;}
case 230:
#line 267 "yacc_syntax.y"
{;
    break;}
case 231:
#line 270 "yacc_syntax.y"
{p(" ");;
    break;}
case 232:
#line 270 "yacc_syntax.y"
{;
    break;}
case 233:
#line 271 "yacc_syntax.y"
{p(" ");;
    break;}
case 234:
#line 271 "yacc_syntax.y"
{;
    break;}
case 235:
#line 272 "yacc_syntax.y"
{p("> ");;
    break;}
case 236:
#line 272 "yacc_syntax.y"
{;
    break;}
case 237:
#line 273 "yacc_syntax.y"
{p("< ");;
    break;}
case 238:
#line 273 "yacc_syntax.y"
{;
    break;}
case 239:
#line 274 "yacc_syntax.y"
{p(" ");;
    break;}
case 240:
#line 274 "yacc_syntax.y"
{;
    break;}
case 241:
#line 275 "yacc_syntax.y"
{p(" ");;
    break;}
case 242:
#line 275 "yacc_syntax.y"
{;
    break;}
case 243:
#line 276 "yacc_syntax.y"
{;
    break;}
case 244:
#line 279 "yacc_syntax.y"
{;
    break;}
case 245:
#line 282 "yacc_syntax.y"
{p("+ ");;
    break;}
case 246:
#line 282 "yacc_syntax.y"
{;
    break;}
case 247:
#line 283 "yacc_syntax.y"
{p("- ");;
    break;}
case 248:
#line 283 "yacc_syntax.y"
{;
    break;}
case 249:
#line 284 "yacc_syntax.y"
{;
    break;}
case 250:
#line 287 "yacc_syntax.y"
{;
    break;}
case 251:
#line 290 "yacc_syntax.y"
{p("* ");;
    break;}
case 252:
#line 290 "yacc_syntax.y"
{;
    break;}
case 253:
#line 291 "yacc_syntax.y"
{p("/ ");;
    break;}
case 254:
#line 291 "yacc_syntax.y"
{;
    break;}
case 255:
#line 292 "yacc_syntax.y"
{;
    break;}
case 256:
#line 295 "yacc_syntax.y"
{;
    break;}
case 257:
#line 296 "yacc_syntax.y"
{;
    break;}
case 258:
#line 297 "yacc_syntax.y"
{p("( ");;
    break;}
case 259:
#line 297 "yacc_syntax.y"
{p(") ");;
    break;}
case 260:
#line 297 "yacc_syntax.y"
{;
    break;}
case 261:
#line 300 "yacc_syntax.y"
{p("");;
    break;}
case 262:
#line 300 "yacc_syntax.y"
{;
    break;}
case 263:
#line 301 "yacc_syntax.y"
{;
    break;}
case 264:
#line 304 "yacc_syntax.y"
{p("- ");;
    break;}
case 265:
#line 304 "yacc_syntax.y"
{;
    break;}
case 266:
#line 305 "yacc_syntax.y"
{p("+ ");;
    break;}
case 267:
#line 305 "yacc_syntax.y"
{;
    break;}
case 268:
#line 308 "yacc_syntax.y"
{p("( ");;
    break;}
case 269:
#line 308 "yacc_syntax.y"
{p(") ");;
    break;}
case 270:
#line 308 "yacc_syntax.y"
{;
    break;}
case 271:
#line 309 "yacc_syntax.y"
{;
    break;}
case 272:
#line 312 "yacc_syntax.y"
{p(" ");;
    break;}
case 273:
#line 312 "yacc_syntax.y"
{;
    break;}
case 274:
#line 315 "yacc_syntax.y"
{p(", ");;
    break;}
case 275:
#line 315 "yacc_syntax.y"
{p(" ");;
    break;}
case 276:
#line 315 "yacc_syntax.y"
{;
    break;}
case 277:
#line 316 "yacc_syntax.y"
{;
    break;}
case 278:
#line 319 "yacc_syntax.y"
{p(" ");;
    break;}
case 279:
#line 319 "yacc_syntax.y"
{;
    break;}
case 280:
#line 320 "yacc_syntax.y"
{p(" ");;
    break;}
case 281:
#line 320 "yacc_syntax.y"
{;
    break;}
case 282:
#line 321 "yacc_syntax.y"
{p(" ");;
    break;}
case 283:
#line 321 "yacc_syntax.y"
{;
    break;}
case 284:
#line 322 "yacc_syntax.y"
{p(" ");;
    break;}
case 285:
#line 322 "yacc_syntax.y"
{;
    break;}
case 286:
#line 323 "yacc_syntax.y"
{p(" ");;
    break;}
case 287:
#line 323 "yacc_syntax.y"
{;
    break;}
case 288:
#line 326 "yacc_syntax.y"
{p(" ");;
    break;}
case 289:
#line 326 "yacc_syntax.y"
{;
    break;}
case 290:
#line 327 "yacc_syntax.y"
{p(" ");;
    break;}
case 291:
#line 327 "yacc_syntax.y"
{;
    break;}
case 292:
#line 328 "yacc_syntax.y"
{p(" ");;
    break;}
case 293:
#line 328 "yacc_syntax.y"
{;
    break;}
case 294:
#line 329 "yacc_syntax.y"
{p(" ");;
    break;}
case 295:
#line 329 "yacc_syntax.y"
{;
    break;}
case 296:
#line 330 "yacc_syntax.y"
{p(" ");;
    break;}
case 297:
#line 330 "yacc_syntax.y"
{;
    break;}
case 298:
#line 333 "yacc_syntax.y"
{;
    break;}
case 299:
#line 334 "yacc_syntax.y"
{;
    break;}
case 300:
#line 337 "yacc_syntax.y"
{p("");;
    break;}
case 301:
#line 337 "yacc_syntax.y"
{;
    break;}
case 302:
#line 340 "yacc_syntax.y"
{p("[ ");;
    break;}
case 303:
#line 340 "yacc_syntax.y"
{p("] ");;
    break;}
case 304:
#line 340 "yacc_syntax.y"
{;
    break;}
case 305:
#line 341 "yacc_syntax.y"
{p(".");;
    break;}
case 306:
#line 341 "yacc_syntax.y"
{;
    break;}
case 307:
#line 342 "yacc_syntax.y"
{p("( ");;
    break;}
case 308:
#line 342 "yacc_syntax.y"
{;
    break;}
case 309:
#line 343 "yacc_syntax.y"
{printf(" ");;
    break;}
case 310:
#line 346 "yacc_syntax.y"
{p(") ");;
    break;}
case 311:
#line 346 "yacc_syntax.y"
{;
    break;}
case 312:
#line 347 "yacc_syntax.y"
{p(") ");;
    break;}
case 313:
#line 347 "yacc_syntax.y"
{;
    break;}
case 314:
#line 350 "yacc_syntax.y"
{;
    break;}
case 315:
#line 353 "yacc_syntax.y"
{p(", ");;
    break;}
case 316:
#line 353 "yacc_syntax.y"
{;
    break;}
case 317:
#line 354 "yacc_syntax.y"
{;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 357 "yacc_syntax.y"
                     /* C code */

void success() {
	printf("\n\033[0;32mparse success\033[0m\n"); 
	exit(1);
}

scopo = 0;
void add_tab(){
	scopo++;
}
void rem_tab(){
	scopo--;
}

void placeTab(){
	int i;
	for (i = 0; i < scopo; i++){
		printf("\t");
	}
}

int main() {
	return yyparse();
}

void p(char *s){
	printf("%s%s", yylval.token->value, s);
	yylval.token->value = "";
}

void yyerror (char *s) {
	fprintf(stderr,"%s:", s);
	//fprintf(stderr,"Line: %d | Column: %d\n ", yylval.token->line, yylval.token->column);
	fprintf(stderr,"%d:%d: No expected '%s'\n", yylval.token->line, yylval.token->column, yylval.token->value);
}
