#ifndef _CONSTANTS_
#define _CONSTANTS_

typedef enum {
	NOT = '!',  
	HEXA_VALUE,		
    INT_VALUE,       
    REAL_VALUE, 
	MOD = '%',
	BOOL_VALUE,
	QUOTE = '\'',
	LPARENT = '(',         
    RPARENT = ')',
    MULT = '*', 
    SUM = '+', 
    COMMA = ',',             
    MINOR = '-',           
    DOT = '.', //ADD NO DOC
    DIVISION = '/',         
    ID,
    INT,
    REAL,
    BOOL,
    STRING,
    VECTOR,      
    PROG,                   
    INIT,              
    END,
    OF,   
    COLON = ':',
    SEMICOMMA = ';',        
    LESS = '<',
    ASSIGN = '=',            
    GREATER = '>',         
    VAR,
    LABEL,           
    STRUCT,         
    TYPE,            
    CONST,           
    RETURN,          
    JUMP,            
    FOR,             
    WHILE,           
    DO,              
    REPEAT,          
    UNTIL,            
    IF,              
    THEN,            
    ELSE,            
    CASE,            
    BE,             
    FUNC,            
    PROC,            
    BREAK,          
    CONTINUE,        
    REF,    
    AND,             
    OR,                 
    LESSEQ,          
    GREATEQ,         
    EQUAL,           
    NOTEQ,    
    LBRACKET = '[', 
    STRING_VALUE,
    RBRACKET = ']',                   
    DOUBLEDOT,             
    CASSIGN,
    FINAL,
    ERROR
    
}KEYWORD;

// namespace non_terminals{

typedef enum {
	PROGRAM_ = ERROR+1,
	BLOCK_,
	PREVDEC_,
	ARRAYDEC_,
	ARRAYDECAUX_,
	RANGELISTAUX_,
	VARDEC_,
	DECWITHASSIGN_,
	USERTYPE_,
	TYPEDEC_,
	TYPEDECAUX_,
	VARDECLISTAUX_,
	LABELDEC_,
	CONSTDEC_,
	PROCDEC_,
	FUNCDEC_,
	PARAMETERS_,
	PARAMSAUX_,
	PARAMSLIST_,
	PREVCOMMAND_,
	CALLCOMMAND_,
	COMMANDSAUX_,
	CALLIDBEGIN_,
	CALLLABEL_,
	WRITE_,
	READ_,
	RETURN_,
	FORLOOP_,
	FORSTRUCT_,
	PREVFOR_,
	VARASSIGNLIST_,
	VARASSIGNLISTAUX_,
	POSFOR_,
	POSFORAUX2_,
	WHILELOOP_,
	REPEATLOOP_,
	IFCOND_,
	IFCONDAUX_,
	CASECOND_,
	CASECONDAUX_,
	CASELISTAUX_,
	CASELISTAUX2_,
	EXPRESSIONLISTAUX_,
	EXPRAND_,
	EXPREQ_,
	EXPRLEQ_,
	LOGICEXPRINTER_,
	EXPRSUM_,
	EXPRMUL_,
	SIMPLEEXPR_,
	OPTRANGE_,
	OPTMINUS_,
	OPTBRACKET_,
	IDLIST_,
	IDLISTAUX_,
	TYPE_,
	LITERAL_,
	ID_,
	IDAUX_,
	ATOMICLISTAUX_,
	DECLARATION_,
	VARCONSTRUCTION_,
	VARDECLIST_,
	ABSTRACTIONDEC_,
	LOOP_,
	CONDITIONAL_,
	BLA_,
	ATOMIC_,
	RANGE_,
	ATOMICLIST_,
	RANGELIST_,
	CASECLAUSE_,
	CASELIST_,
	NUMERICEXPRINTER_,
	COMMANDS_,
	NUMERICEXPR_,
	POSFORAUX_,
	LOGICEXPR_,
	EXPRESSION_,
	EXPRESSIONLIST_
} NONTERMINALS;
// };

bool is_terminal(int value){
	if(value >= NOT && value <= ERROR)
		return true;
	return false;
}

bool is_non_terminal(int value){
	if(value >= PROGRAM_ && value <= EXPRESSIONLIST_)
		return true;
	return false;
}

#endif